// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type BenchmarkEdge struct {
	Node   *Benchmark `json:"node"`
	Cursor string     `json:"cursor"`
}

type BenchmarkRun struct {
	ID          string             `json:"id"`
	BenchmarkID string             `json:"benchmarkId"`
	Status      BenchmarkStatus    `json:"status"`
	Results     []*BenchmarkResult `json:"results"`
	StartedAt   time.Time          `json:"startedAt"`
	CompletedAt *time.Time         `json:"completedAt,omitempty"`
	Error       *string            `json:"error,omitempty"`
}

type DateRange struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type Key struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Provider  *Provider `json:"provider"`
	Value     string    `json:"value"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
}

type Metric struct {
	Name     string         `json:"name"`
	Value    float64        `json:"value"`
	Unit     *string        `json:"unit,omitempty"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

type Mutation struct {
}

type ProviderAccount struct {
	ID             string         `json:"id"`
	ProviderID     string         `json:"providerId"`
	Provider       *Provider      `json:"provider"`
	Name           string         `json:"name"`
	Status         AccountStatus  `json:"status"`
	QuotaRemaining *float64       `json:"quotaRemaining,omitempty"`
	QuotaLimit     *float64       `json:"quotaLimit,omitempty"`
	Models         []*Model       `json:"models"`
	Metadata       map[string]any `json:"metadata,omitempty"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
}

type Query struct {
}

type Subscription struct {
}

type AccountStatus string

const (
	AccountStatusActive             AccountStatus = "ACTIVE"
	AccountStatusSuspended          AccountStatus = "SUSPENDED"
	AccountStatusQuotaExceeded      AccountStatus = "QUOTA_EXCEEDED"
	AccountStatusInvalidCredentials AccountStatus = "INVALID_CREDENTIALS"
)

var AllAccountStatus = []AccountStatus{
	AccountStatusActive,
	AccountStatusSuspended,
	AccountStatusQuotaExceeded,
	AccountStatusInvalidCredentials,
}

func (e AccountStatus) IsValid() bool {
	switch e {
	case AccountStatusActive, AccountStatusSuspended, AccountStatusQuotaExceeded, AccountStatusInvalidCredentials:
		return true
	}
	return false
}

func (e AccountStatus) String() string {
	return string(e)
}

func (e *AccountStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccountStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccountStatus", str)
	}
	return nil
}

func (e AccountStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccountStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccountStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProviderType string

const (
	ProviderTypeOpenai    ProviderType = "OPENAI"
	ProviderTypeAnthropic ProviderType = "ANTHROPIC"
	ProviderTypeGoogle    ProviderType = "GOOGLE"
	ProviderTypeMistral   ProviderType = "MISTRAL"
	ProviderTypeCohere    ProviderType = "COHERE"
	ProviderTypeCustom    ProviderType = "CUSTOM"
)

var AllProviderType = []ProviderType{
	ProviderTypeOpenai,
	ProviderTypeAnthropic,
	ProviderTypeGoogle,
	ProviderTypeMistral,
	ProviderTypeCohere,
	ProviderTypeCustom,
}

func (e ProviderType) IsValid() bool {
	switch e {
	case ProviderTypeOpenai, ProviderTypeAnthropic, ProviderTypeGoogle, ProviderTypeMistral, ProviderTypeCohere, ProviderTypeCustom:
		return true
	}
	return false
}

func (e ProviderType) String() string {
	return string(e)
}

func (e *ProviderType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProviderType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProviderType", str)
	}
	return nil
}

func (e ProviderType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProviderType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProviderType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
