// Package model contains GraphQL model types
// Most types will be generated by gqlgen, but we define some custom types here
package model

import (
	"time"
)

// Model represents an LLM model
type Model struct {
	ID              string        `json:"id"`
	Name            string        `json:"name"`
	Provider        *Provider     `json:"provider"`
	DisplayName     string        `json:"displayName"`
	Description     *string       `json:"description,omitempty"`
	Capabilities    []Capability  `json:"capabilities"`
	ContextWindow   int           `json:"contextWindow"`
	MaxOutputTokens *int          `json:"maxOutputTokens,omitempty"`
	InputPrice      float64       `json:"inputPrice"`
	OutputPrice     float64       `json:"outputPrice"`
	Available       bool          `json:"available"`
	Deprecated      bool          `json:"deprecated"`
	DeprecationDate *time.Time    `json:"deprecationDate,omitempty"`
	Metrics         *ModelMetrics `json:"metrics,omitempty"`
	UsageStats      *ModelUsageStats `json:"usageStats,omitempty"`
	RelatedModels   []*Model      `json:"relatedModels"`
	Version         *string       `json:"version,omitempty"`
	ReleaseDate     *time.Time    `json:"releaseDate,omitempty"`
	Metadata        map[string]interface{} `json:"metadata,omitempty"`
	CreatedAt       time.Time     `json:"createdAt"`
	UpdatedAt       time.Time     `json:"updatedAt"`
}

// ModelMetrics contains performance metrics for a model
type ModelMetrics struct {
	LatencyP50        float64   `json:"latencyP50"`
	LatencyP90        float64   `json:"latencyP90"`
	LatencyP99        float64   `json:"latencyP99"`
	TokensPerSecond   float64   `json:"tokensPerSecond"`
	RequestsPerMinute float64   `json:"requestsPerMinute"`
	ErrorRate         float64   `json:"errorRate"`
	QualityScore      *float64  `json:"qualityScore,omitempty"`
	Window            string    `json:"window"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

// ModelUsageStats contains usage statistics for a model
type ModelUsageStats struct {
	TotalRequests int             `json:"totalRequests"`
	TotalTokens   int             `json:"totalTokens"`
	TotalCost     float64         `json:"totalCost"`
	Period        string          `json:"period"`
	ByTaskType    []*TaskTypeUsage `json:"byTaskType"`
	ByDomain      []*DomainUsage   `json:"byDomain"`
}

type TaskTypeUsage struct {
	TaskType string `json:"taskType"`
	Requests int    `json:"requests"`
	Tokens   int    `json:"tokens"`
}

type DomainUsage struct {
	Domain   string `json:"domain"`
	Requests int    `json:"requests"`
	Tokens   int    `json:"tokens"`
}

// ModelConnection for pagination
type ModelConnection struct {
	Nodes      []*Model  `json:"nodes"`
	PageInfo   *PageInfo `json:"pageInfo"`
	TotalCount int       `json:"totalCount"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

// Provider represents an LLM provider
type Provider struct {
	ID                string            `json:"id"`
	Name              string            `json:"name"`
	DisplayName       string            `json:"displayName"`
	Status            ProviderStatus    `json:"status"`
	StatusMessage     *string           `json:"statusMessage,omitempty"`
	LastCheck         time.Time         `json:"lastCheck"`
	Models            []*Model          `json:"models"`
	AvailableModels   int               `json:"availableModels"`
	TotalModels       int               `json:"totalModels"`
	Accounts          []*Account        `json:"accounts"`
	RateLimit         *RateLimitInfo    `json:"rateLimit,omitempty"`
	Metrics           *ProviderMetrics  `json:"metrics,omitempty"`
	BaseURL           string            `json:"baseUrl"`
	SupportedFeatures []string          `json:"supportedFeatures"`
	Metadata          map[string]interface{} `json:"metadata,omitempty"`
	CreatedAt         time.Time         `json:"createdAt"`
	UpdatedAt         time.Time         `json:"updatedAt"`
}

// Account represents a provider account
type Account struct {
	ID             string     `json:"id"`
	Provider       *Provider  `json:"provider"`
	Name           string     `json:"name"`
	Active         bool       `json:"active"`
	LastUsed       *time.Time `json:"lastUsed,omitempty"`
	QuotaRemaining *float64   `json:"quotaRemaining,omitempty"`
	QuotaLimit     *float64   `json:"quotaLimit,omitempty"`
	QuotaResetAt   *time.Time `json:"quotaResetAt,omitempty"`
	RateLimit      *RateLimitInfo `json:"rateLimit,omitempty"`
	AllowedModels  []string   `json:"allowedModels,omitempty"`
	UsageThisMonth *float64   `json:"usageThisMonth,omitempty"`
	UsageLimit     *float64   `json:"usageLimit,omitempty"`
	TokenExpiresAt *time.Time `json:"tokenExpiresAt,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      time.Time  `json:"updatedAt"`
}

type RateLimitInfo struct {
	Remaining int       `json:"remaining"`
	Limit     int       `json:"limit"`
	ResetAt   time.Time `json:"resetAt"`
	Unit      string    `json:"unit"`
}

type ProviderMetrics struct {
	AvgLatencyMs      float64   `json:"avgLatencyMs"`
	P50LatencyMs      float64   `json:"p50LatencyMs"`
	P99LatencyMs      float64   `json:"p99LatencyMs"`
	ErrorRate         float64   `json:"errorRate"`
	Uptime            float64   `json:"uptime"`
	RequestsPerMinute float64   `json:"requestsPerMinute"`
	TokensPerMinute   float64   `json:"tokensPerMinute"`
	AvgCostPerRequest float64   `json:"avgCostPerRequest"`
	Window            string    `json:"window"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

// HealthStatus represents the health status
type HealthStatus struct {
	Status    string    `json:"status"`
	Version   string    `json:"version"`
	Timestamp time.Time `json:"timestamp"`
}

// CreateModelInput represents input for creating a model
type CreateModelInput struct {
	Name            string       `json:"name"`
	ProviderID      string       `json:"providerId"`
	DisplayName     string       `json:"displayName"`
	Description     *string      `json:"description,omitempty"`
	Capabilities    []Capability `json:"capabilities"`
	ContextWindow   int          `json:"contextWindow"`
	MaxOutputTokens *int         `json:"maxOutputTokens,omitempty"`
}

// UpdateModelInput represents input for updating a model
type UpdateModelInput struct {
	Name            *string       `json:"name,omitempty"`
	DisplayName     *string       `json:"displayName,omitempty"`
	Description     *string       `json:"description,omitempty"`
	Capabilities    []Capability  `json:"capabilities,omitempty"`
	ContextWindow   *int          `json:"contextWindow,omitempty"`
	MaxOutputTokens *int          `json:"maxOutputTokens,omitempty"`
	Available       *bool         `json:"available,omitempty"`
}


// ResolverRoot is the root resolver type
type ResolverRoot interface {
	Query() QueryResolver
	Mutation() MutationResolver
	Subscription() SubscriptionResolver
}

// QueryResolver handles Query fields
type QueryResolver interface {
}

// MutationResolver handles Mutation fields
type MutationResolver interface {
}

// SubscriptionResolver handles Subscription fields
type SubscriptionResolver interface {
}
