/**
 * APIKEY provider catalog — part 3 of 3 (god-file decomposition).
 * Pure data; merged by apikey.ts via spread. No behavior change; order preserved.
 */
export const APIKEY_PROVIDERS_PART3 = {
  nanogpt: {
    id: "nanogpt",
    alias: "nanogpt",
    name: "NanoGPT",
    icon: "chat",
    color: "#4F46E5",
    textIcon: "NG",
    website: "https://nano-gpt.com",
  },
  predibase: {
    id: "predibase",
    alias: "predibase",
    name: "Predibase",
    icon: "deployed_code_history",
    color: "#0F766E",
    textIcon: "PB",
    website: "https://predibase.com",
    hasFree: false,
    freeNote: "$25 free trial credits (30-day validity)",
    subscriptionRisk: true,
    riskNoticeVariant: "deprecated",
    deprecated: true,
    deprecationReason:
      "serving.app.predibase.com no longer resolves (sweep 2026-06-19); the managed serving API appears discontinued.",
  },
  bytez: {
    id: "bytez",
    alias: "bytez",
    name: "Bytez",
    icon: "api",
    color: "#6366F1",
    textIcon: "BZ",
    website: "https://bytez.com",
    hasFree: true,
    freeNote: "$1 free credits, refreshes every 4 weeks",
  },
  aimlapi: {
    id: "aimlapi",
    alias: "aiml",
    name: "AI/ML API",
    icon: "hub",
    color: "#6366F1",
    textIcon: "AI",
    website: "https://aimlapi.com",
    hasFree: false,
    freeNote:
      "Free tier paused (2026) — AI/ML API is now pay-as-you-go only (min $20 top-up); no recurring free credits.",
    passthroughModels: true,
  },
  novita: {
    id: "novita",
    alias: "novita",
    name: "Novita AI",
    icon: "auto_awesome",
    color: "#FF4081",
    textIcon: "NV",
    website: "https://novita.ai",
    hasFree: true,
    freeNote: "$0.50 trial credits on signup (valid about 1 year)",
    passthroughModels: true,
  },
  piapi: {
    id: "piapi",
    alias: "pi",
    name: "PiAPI",
    icon: "api",
    color: "#7C4DFF",
    textIcon: "PI",
    website: "https://piapi.ai",
    passthroughModels: true,
  },
  getgoapi: {
    id: "getgoapi",
    alias: "ggo",
    name: "GoAPI",
    icon: "rocket_launch",
    color: "#FF6D00",
    textIcon: "GO",
    website: "https://api.getgoapi.com",
    passthroughModels: true,
  },
  laozhang: {
    id: "laozhang",
    alias: "lz",
    name: "LaoZhang AI",
    icon: "hub",
    color: "#FF1744",
    textIcon: "LZ",
    website: "https://api.laozhang.ai",
    passthroughModels: true,
  },
  glhf: {
    id: "glhf",
    alias: "glhf",
    name: "GLHF Chat",
    icon: "hub",
    color: "#10B981",
    textIcon: "GH",
    website: "https://glhf.chat",
    authHint: "Bearer API key for the GLHF OpenAI-compatible gateway.",
    hasFree: false,
    freeNote: "Discontinued 2026 — glhf.chat free beta ended; no free tier.",
    passthroughModels: true,
    subscriptionRisk: true,
    riskNoticeVariant: "deprecated",
    deprecated: true,
    deprecationReason:
      "glhf.chat shut down (2026); its api.laf.run gateway no longer serves the catalog (sweep 2026-06-19).",
  },
  cablyai: {
    id: "cablyai",
    alias: "cablyai",
    name: "CablyAI",
    icon: "hub",
    color: "#FF4081",
    textIcon: "CA",
    website: "https://cablyai.com",
    authHint: "Bearer API key for the CablyAI OpenAI-compatible gateway.",
    passthroughModels: true,
  },
  thebai: {
    id: "thebai",
    alias: "thebai",
    name: "TheB.AI",
    icon: "hub",
    color: "#3B82F6",
    textIcon: "TB",
    website: "https://theb.ai",
    authHint: "Bearer API key for the TheB.AI OpenAI-compatible gateway.",
    passthroughModels: true,
  },
  fenayai: {
    id: "fenayai",
    alias: "fenayai",
    name: "FenayAI",
    icon: "hub",
    color: "#FF9800",
    textIcon: "FN",
    website: "https://fenayai.com",
    authHint: "Bearer API key for the FenayAI OpenAI-compatible gateway.",
    passthroughModels: true,
  },
  empower: {
    id: "empower",
    alias: "empower",
    name: "Empower",
    icon: "hub",
    color: "#14B8A6",
    textIcon: "EM",
    website: "https://docs.empower.dev",
    authHint: "Bearer API key for the Empower OpenAI-compatible endpoint.",
    apiHint:
      "Empower exposes OpenAI-compatible chat on https://app.empower.dev/api/v1 with tool-calling support on empower-functions.",
    passthroughModels: true,
  },
  "nous-research": {
    id: "nous-research",
    alias: "nous",
    name: "Nous Research",
    icon: "hub",
    color: "#2563EB",
    textIcon: "NO",
    website: "https://portal.nousresearch.com/help",
    authHint:
      "Use your Nous Portal API key. OmniRoute targets the official OpenAI-compatible inference endpoint at https://inference-api.nousresearch.com/v1.",
    apiHint:
      "Nous exposes an OpenAI-compatible /v1 surface with a large remote /models catalog. The /chat/completions endpoint requires a valid API key for programmatic inference.",
    hasFree: true,
    freeNote: "Free tier: 50 RPM, 500,000 TPM — no credit card",
  },
  poe: {
    id: "poe",
    alias: "poe",
    name: "Poe",
    icon: "hub",
    color: "#F97316",
    textIcon: "PO",
    website: "https://creator.poe.com/api-reference",
    authHint: "Bearer API key for the Poe OpenAI-compatible API.",
    apiHint:
      "Poe exposes OpenAI-compatible chat and responses on https://api.poe.com/v1, with authenticated balance checks on /usage/current_balance.",
    passthroughModels: true,
  },
  gitlab: {
    id: "gitlab",
    alias: "gitlab",
    name: "GitLab Duo PAT",
    icon: "hub",
    color: "#FC6D26",
    textIcon: "GL",
    website: "https://docs.gitlab.com/user/duo_agent_platform/code_suggestions/",
    authHint:
      "GitLab personal access token for the public Code Suggestions API. Configure a self-hosted base URL when not using gitlab.com.",
  },
  chutes: {
    id: "chutes",
    alias: "chutes",
    name: "Chutes.ai",
    icon: "hub",
    color: "#06B6D4",
    textIcon: "CH",
    website: "https://chutes.ai",
    hasFree: false,
    freeNote:
      "No free tier as of 2026 — Chutes moved to pay-as-you-go (free Early Access ended 2026-03).",
    authHint: "Bearer API key for the Chutes OpenAI-compatible gateway.",
    passthroughModels: true,
  },
  "voyage-ai": {
    id: "voyage-ai",
    alias: "voyage",
    name: "Voyage AI",
    icon: "blur_on",
    color: "#0F766E",
    textIcon: "VA",
    website: "https://www.voyageai.com",
    authHint: "Bearer API key for Voyage AI embeddings and rerank APIs.",
    hasFree: true,
    freeNote: "200M free tokens for embeddings and reranking",
  },
  "jina-ai": {
    id: "jina-ai",
    alias: "jina",
    name: "Jina AI",
    icon: "sort",
    color: "#2563EB",
    textIcon: "JA",
    website: "https://jina.ai",
    authHint: "Bearer API key for the Jina AI rerank API.",
    hasFree: true,
    freeNote: "10M free tokens on signup (non-commercial), no credit card required",
  },
  "fal-ai": {
    id: "fal-ai",
    alias: "fal",
    name: "Fal.ai",
    icon: "image",
    color: "#2563EB",
    textIcon: "FL",
    website: "https://fal.ai",
  },
  "stability-ai": {
    id: "stability-ai",
    alias: "stability",
    name: "Stability AI",
    icon: "image",
    color: "#8B5CF6",
    textIcon: "SA",
    website: "https://stability.ai",
  },
  "black-forest-labs": {
    id: "black-forest-labs",
    alias: "bfl",
    name: "Black Forest Labs",
    icon: "image",
    color: "#111827",
    textIcon: "BF",
    website: "https://blackforestlabs.ai",
  },
  recraft: {
    id: "recraft",
    alias: "recraft",
    name: "Recraft",
    icon: "image",
    color: "#EC4899",
    textIcon: "RC",
    website: "https://recraft.ai",
  },
  topaz: {
    id: "topaz",
    alias: "topaz",
    name: "Topaz",
    icon: "image",
    color: "#059669",
    textIcon: "TP",
    website: "https://topazlabs.com",
  },
  baidu: {
    id: "baidu",
    alias: "baidu",
    name: "Baidu (ERNIE)",
    icon: "auto_awesome",
    color: "#2932E1",
    textIcon: "BD",
    website: "https://yiyan.baidu.com",
    hasFree: true,
    freeNote: "Free ERNIE Speed/Lite models. China's #2 LLM.",
    passthroughModels: true,
    authHint: "Get API key at console.bce.baidu.com",
  },
  tencent: {
    id: "tencent",
    alias: "tencent",
    name: "Tencent Hunyuan",
    icon: "auto_awesome",
    color: "#07C160",
    textIcon: "TC",
    website: "https://hunyuan.tencent.com",
    hasFree: true,
    freeNote: "Free Hunyuan Lite models. WeChat ecosystem.",
    passthroughModels: true,
    authHint: "Get API key at console.cloud.tencent.com",
  },
  iflytek: {
    id: "iflytek",
    alias: "iflytek",
    name: "iFlytek Spark",
    icon: "auto_awesome",
    color: "#0066FF",
    textIcon: "IF",
    website: "https://xinghuo.xfyun.cn",
    hasFree: true,
    freeNote:
      "Spark Lite is free (2 QPS rate-limited), but iFlytek ToS §2.4(3) prohibits programmatic extraction and requires Chinese real-name auth — use with caution.",
    passthroughModels: true,
    authHint: "Get API key at console.xfyun.cn",
  },
  baichuan: {
    id: "baichuan",
    alias: "baichuan",
    name: "Baichuan",
    icon: "auto_awesome",
    color: "#6366F1",
    textIcon: "BC",
    website: "https://baichuan.com",
    hasFree: true,
    freeNote: "Free Baichuan models. Popular Chinese LLM startup.",
    passthroughModels: true,
    authHint: "Get API key at platform.baichuan-ai.com",
  },
  yi: {
    id: "yi",
    alias: "yi",
    name: "Yi (01.AI)",
    icon: "auto_awesome",
    color: "#10B981",
    textIcon: "YI",
    website: "https://01.ai",
    hasFree: false,
    freeNote:
      "No free API tier (2026) — Yi-Light retired; platform.01.ai is pay-as-you-go (Yi-Lightning paid). Open weights are download-only.",
    passthroughModels: true,
    authHint: "Get API key at platform.lingyiwanwu.com",
  },
  stepfun: {
    id: "stepfun",
    alias: "stepfun",
    name: "StepFun",
    icon: "auto_awesome",
    color: "#8B5CF6",
    textIcon: "SF",
    website: "https://stepfun.com",
    hasFree: true,
    freeNote: "Free Step-2 models. Chinese AI company.",
    passthroughModels: true,
    authHint: "Get API key at platform.stepfun.com",
  },
  coze: {
    id: "coze",
    alias: "coze",
    name: "Coze",
    icon: "smart_toy",
    color: "#3B82F6",
    textIcon: "CZ",
    website: "https://coze.com",
    hasFree: true,
    freeNote: "Free ByteDance agent platform. Bot building + LLM access.",
    passthroughModels: true,
    authHint: "Get API key at coze.com/open/api",
  },
  "360ai": {
    id: "360ai",
    alias: "360ai",
    name: "360 AI",
    icon: "auto_awesome",
    color: "#00B96B",
    textIcon: "360",
    website: "https://ai.360.cn",
    hasFree: true,
    freeNote: "Free 360 AI Brain models. Major Chinese security company.",
    passthroughModels: true,
    authHint: "Get API key at ai.360.cn",
  },
  doubao: {
    id: "doubao",
    alias: "doubao",
    name: "Doubao",
    icon: "auto_awesome",
    color: "#FE2C55",
    textIcon: "DB",
    website: "https://doubao.com",
    hasFree: true,
    freeNote: "Free Doubao models. ByteDance's chatbot.",
    passthroughModels: true,
    authHint: "Get API key at console.volcengine.com",
  },
  sensenova: {
    id: "sensenova",
    alias: "sensenova",
    name: "SenseNova",
    icon: "auto_awesome",
    color: "#0066FF",
    textIcon: "SN",
    website: "https://platform.sensenova.cn",
    hasFree: true,
    freeNote: "Free SenseTime models. Computer vision leader.",
    passthroughModels: true,
    authHint: "Get API key at platform.sensenova.cn",
  },
  sparkdesk: {
    id: "sparkdesk",
    alias: "sparkdesk",
    name: "SparkDesk",
    icon: "auto_awesome",
    color: "#0066FF",
    textIcon: "SD",
    website: "https://xinghuo.xfyun.cn",
    hasFree: true,
    freeNote:
      "Spark Lite free (alias for iflytek), but ToS restricts to personal/non-commercial use and prohibits relaying access to third parties — use with caution.",
    passthroughModels: true,
    authHint: "Get API key at console.xfyun.cn",
  },
  phind: {
    id: "phind",
    alias: "phind",
    name: "Phind",
    icon: "search",
    color: "#EC4899",
    textIcon: "PH",
    website: "https://phind.com",
    hasFree: false,
    freeNote: "Discontinued 2026 — phind.com shut down (2026-01); no free tier.",
    passthroughModels: true,
    authHint: "Get API key at phind.com",
  },
  huggingchat: {
    id: "huggingchat",
    alias: "huggingchat",
    name: "HuggingChat",
    icon: "chat",
    color: "#FFD21E",
    textIcon: "HC",
    website: "https://huggingface.co/chat",
    hasFree: true,
    freeNote: "Free chat with open models (Llama, Mistral, etc.).",
    passthroughModels: true,
    authHint: "No API key required for basic access.",
  },
  dify: {
    id: "dify",
    alias: "dify",
    name: "Dify",
    icon: "smart_toy",
    color: "#6366F1",
    textIcon: "DF",
    website: "https://dify.ai",
    hasFree: true,
    freeNote: "Free open-source AI app builder + RAG platform.",
    passthroughModels: true,
    authHint: "Get API key from your Dify instance.",
  },
  "arcee-ai": {
    id: "arcee-ai",
    alias: "arcee",
    name: "Arcee AI",
    icon: "auto_awesome",
    color: "#8B5CF6",
    textIcon: "AR",
    website: "https://arcee.ai",
    hasFree: true,
    freeNote: "Free Trinity Large Thinking model (262K context). No credit card required.",
    passthroughModels: true,
    authHint: "Get API key at arcee.ai",
  },
  inclusionai: {
    id: "inclusionai",
    alias: "inclusion",
    name: "InclusionAI",
    icon: "psychology",
    color: "#10B981",
    textIcon: "IA",
    website: "https://inclusionai.com",
    hasFree: true,
    freeNote: "Free Ling-2.6-flash model (1T-param MoE, 262K context). No credit card required.",
    passthroughModels: true,
    authHint: "Get API key at inclusionai.com",
    subscriptionRisk: true,
    riskNoticeVariant: "deprecated",
    deprecated: true,
    deprecationReason:
      "api.inclusionai.tech no longer resolves (sweep 2026-06-19); the inference API appears discontinued.",
  },
  liquid: {
    id: "liquid",
    alias: "liquid",
    name: "Liquid AI",
    icon: "water_drop",
    color: "#06B6D4",
    textIcon: "LQ",
    website: "https://liquid.ai",
    hasFree: true,
    freeNote:
      "Free LFM2.5-1.2B-Thinking and LFM2.5-1.2B-Instruct models. MIT spinoff, hybrid architecture.",
    passthroughModels: true,
    authHint: "Get API key at liquid.ai",
  },
  nomic: {
    id: "nomic",
    alias: "nomic",
    name: "Nomic",
    icon: "hub",
    color: "#7C3AED",
    textIcon: "NM",
    website: "https://nomic.ai",
    hasFree: true,
    freeNote: "Free Nomic Embed API. Open-source embeddings, no credit card required.",
    passthroughModels: true,
    authHint: "Get API key at atlas.nomic.ai",
  },
  monsterapi: {
    id: "monsterapi",
    alias: "monster",
    name: "MonsterAPI",
    icon: "cloud",
    color: "#EF4444",
    textIcon: "MA",
    website: "https://monsterapi.ai",
    hasFree: true,
    freeNote:
      "One-time signup trial credits for decentralized GPU inference (no recurring free plan). No credit card required.",
    passthroughModels: true,
    authHint: "Get API key at monsterapi.ai",
  },
  // ── Web Fetch Providers ─────────────────────────────────────────────────────
  firecrawl: {
    id: "firecrawl",
    alias: "fc",
    name: "Firecrawl",
    icon: "language",
    color: "#FB923C",
    textIcon: "FC",
    website: "https://firecrawl.dev",
    hasFree: true,
    notice: {
      text: "Free tier: 500 fetches/month, no credit card needed.",
      apiKeyUrl: "https://firecrawl.dev/app/api-keys",
    },
    serviceKinds: ["webFetch"],
  },
  "jina-reader": {
    id: "jina-reader",
    alias: "jr",
    name: "Jina Reader",
    icon: "menu_book",
    color: "#0EA5E9",
    textIcon: "JR",
    website: "https://jina.ai/reader",
    hasFree: true,
    notice: {
      text: "Free tier: 1M fetches/month.",
      apiKeyUrl: "https://jina.ai/api-dashboard",
    },
    serviceKinds: ["webFetch"],
  },
  byteplus: {
    id: "byteplus",
    alias: "bpm",
    name: "BytePlus ModelArk",
    icon: "cloud",
    color: "#2563EB",
    textIcon: "BP",
    website: "https://console.byteplus.com/ark",
    hasFree: true,
    notice: {
      text: "Free credits for new accounts. Seed 2.0, Kimi K2 Thinking, GLM 4.7, GPT-OSS-120B available.",
      apiKeyUrl: "https://console.byteplus.com/ark/region:ark+ap-southeast-1/apiKey",
    },
    serviceKinds: ["llm"],
  },
  bluesminds: {
    id: "bluesminds",
    alias: "bm",
    name: "BluesMinds",
    icon: "psychology",
    color: "#3B82F6",
    textIcon: "BM",
    website: "https://www.bluesminds.com",
    hasFree: true,
    freeNote:
      "Free daily pi credits — supports 200+ models including GPT-4o, GPT-4.1, Claude Sonnet 4.5, Gemini 2.0 Flash, DeepSeek V4, Qwen, Kimi K2",
    apiHint:
      "Get your API key at https://www.bluesminds.com — OpenAI-compatible endpoint at https://api.bluesminds.com/v1 with free daily credits. VIP models (Claude Opus 4.5, Gemini 2.5 Pro) consume pi credits.",
  },
  "freemodel-dev": {
    id: "freemodel-dev",
    alias: "fmd",
    name: "FreeModel.dev",
    icon: "auto_awesome",
    color: "#8B5CF6",
    textIcon: "FM",
    website: "https://freemodel.dev",
    hasFree: true,
    freeNote:
      "$300 free credits on signup — no credit card required. Access GPT-5.4 and GPT-5.5 (OpenAI's latest flagship models) through an OpenAI-compatible API.",
    apiHint:
      "Get $300 free API credits at https://freemodel.dev — no payment info required. OpenAI-compatible endpoint. GPT-5.4 and GPT-5.5 models available.",
  },
  freeaiapikey: {
    id: "freeaiapikey",
    alias: "faik",
    name: "FreeAIAPIKey",
    icon: "vpn_key",
    color: "#F59E0B",
    textIcon: "FK",
    website: "https://freeaiapikey.com",
    apiHint:
      "Discounted API proxy for 40+ models including GPT-5, Claude Opus 4.6, Claude Sonnet 4.6, Qwen 3.5. Get your API key at https://freeaiapikey.com/dashboard. Base URL: https://freeaiapikey.com/v1.",
  },
  zenmux: {
    id: "zenmux",
    alias: "zm",
    name: "ZenMux",
    icon: "neurology",
    color: "#7C3AED",
    textIcon: "ZM",
    website: "https://zenmux.ai",
    hasFree: true,
    freeNote:
      "Free tier includes access to Gemini 3 Flash, DeepSeek V3.2, Grok 4.1 Fast, Mistral Large, and more. Get your API key at https://zenmux.ai.",
    authHint:
      "Use your ZenMux API key in Authorization: Bearer <key>. ZenMux is fully OpenAI-compatible. Base URL: https://zenmux.ai/api/v1.",
    apiHint:
      "ZenMux exposes an OpenAI-compatible chat completions endpoint at /api/v1/chat/completions, plus Anthropic Messages (/api/anthropic/v1/messages) and Google Gemini (/api/vertex-ai) protocol surfaces. OmniRoute uses the OpenAI protocol.",
  },
  openadapter: {
    id: "openadapter",
    alias: "oad",
    name: "OpenAdapter",
    icon: "hub",
    color: "#10B981",
    textIcon: "OD",
    website: "https://openadapter.dev",
    hasFree: true,
    freeNote:
      "Free tier with a generous quota and no credit card — 15+ open-source models with daily quota. Get your API key at https://dashboard.openadapter.in.",
    authHint:
      "Use your OpenAdapter API key in Authorization: Bearer sk-cv-<key>. Fully OpenAI-compatible. API base URL: https://api.openadapter.in/v1.",
    apiHint:
      "OpenAdapter exposes an OpenAI-compatible chat completions endpoint at https://api.openadapter.in/v1/chat/completions, aggregating 70+ open-source models (DeepSeek, Qwen, Kimi, MiniMax, GLM, Llama, Mistral, …). OmniRoute uses the OpenAI protocol.",
  },
  dit: {
    id: "dit",
    alias: "dai",
    name: "DIT.ai",
    icon: "hub",
    color: "#0EA5E9",
    textIcon: "DT",
    website: "https://dit.ai",
    authHint:
      "Use your dit.ai API key in Authorization: Bearer <key>. Fully OpenAI-compatible — a drop-in replacement, just change the base URL to https://api.dit.ai/v1.",
    apiHint:
      "dit.ai (Distributed Intelligence Trade) is an OpenAI-compatible router/gateway with dynamic per-request pricing, exposing /v1/chat/completions at https://api.dit.ai/v1. OmniRoute uses the OpenAI protocol; spend/savings analytics live in the dit.ai dashboard.",
  },
  tokenrouter: {
    id: "tokenrouter",
    alias: "trk",
    name: "TokenRouter",
    icon: "hub",
    color: "#F59E0B",
    textIcon: "TK",
    website: "https://tokenrouter.com",
    hasFree: true,
    freeNote:
      "Free tier includes the MiniMax 3 model. Get your API key at https://tokenrouter.com.",
    authHint:
      "Use your TokenRouter API key in Authorization: Bearer <key>. Fully OpenAI-compatible. API base URL: https://api.tokenrouter.com/v1.",
    apiHint:
      "TokenRouter exposes an OpenAI-compatible chat completions endpoint at https://api.tokenrouter.com/v1/chat/completions, plus a working /v1/models catalog. OmniRoute uses the OpenAI protocol.",
  },
};
