changelog:
  categories:
    - title: Breaking changes
      labels:
        - breaking
    - title: Enhancements
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Other changes
      labels:
        - "*"
