#!/usr/bin/env python3
"""
generate_heroine_ref_imagen3.py — Generate canonical SATC heroine reference image
using Google Vertex AI Imagen 3 (`imagen-3.0-generate-002`) for Veo character consistency.

Usage:
  python3 scripts/generate_heroine_ref_imagen3.py [--output assets/heroine_reference.png]
"""

import argparse
import os
import sys
from pathlib import Path

# Default config
DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "assets" / "heroine_reference.png"
DEFAULT_PROJECT = os.environ.get("GOOGLE_CLOUD_PROJECT", "project-f91a723f-af1b-4dd2-ba3")
DEFAULT_LOCATION = os.environ.get("GOOGLE_CLOUD_LOCATION", "europe-west3")

IMAGEN_PROMPT = (
    "Full-body portrait of a stylish woman in her early 30s standing confidently on a Manhattan "
    "sidewalk at golden hour. Long natural wavy honey-blonde hair with warm highlights. Bold bright "
    "red-pink lipstick, rosy cheeks, blue-grey eyes with subtle winged eyeliner. Sleeveless pale pink "
    "fitted tank top, layered white tulle ballet skirt mid-thigh. Warm golden hour sunlight from right side. "
    "City bokeh background. HBO prestige TV 1998 look, 35mm film grain, rich warm-cool contrast, glossy premium. "
    "No text. No watermarks."
)


def generate_reference_image(output_path: Path, project_id: str, location: str, dry_run: bool = False):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    print(f"🎨 Generating Heroine Reference Image via Imagen 3...")
    print(f"   Project: {project_id} | Location: {location}")
    print(f"   Output:  {output_path}")
    print(f"   Prompt:  {IMAGEN_PROMPT[:100]}...")

    if dry_run:
        print("⏭️  Dry run mode enabled. Exiting cleanly.")
        return True

    try:
        from google import genai
        from google.genai import types

        client = genai.Client(vertexai=True, project=project_id, location=location)

        response = client.models.generate_images(
            model="imagen-3.0-generate-002",
            prompt=IMAGEN_PROMPT,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio="16:9",
                person_generation="ALLOW_ADULT",
                output_mime_type="image/png",
            ),
        )

        if response.generated_images:
            img = response.generated_images[0]
            with open(output_path, "wb") as f:
                f.write(img.image.image_bytes)
            file_size = output_path.stat().st_size / 1024
            print(f"✅ Successfully saved reference image: {output_path} ({file_size:.1f} KB)")
            return True
        else:
            print("❌ No image generated by Imagen 3.")
            return False

    except Exception as e:
        print(f"❌ Error generating reference image: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Generate canonical heroine reference image via Imagen 3.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Output image file path")
    parser.add_argument("--project", default=DEFAULT_PROJECT, help="Google Cloud Project ID")
    parser.add_argument("--location", default=DEFAULT_LOCATION, help="Vertex AI location")
    parser.add_argument("--dry-run", action="store_true", help="Print config without calling API")
    args = parser.parse_args()

    success = generate_reference_image(args.output, args.project, args.location, args.dry_run)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
