// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearExpiredCooldowns = `-- name: ClearExpiredCooldowns :exec
UPDATE model_endpoints 
SET status = 'active', cooldown_until = NULL, updated_at = NOW()
WHERE status = 'cooldown' AND cooldown_until < NOW()
`

func (q *Queries) ClearExpiredCooldowns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearExpiredCooldowns)
	return err
}

const createAccountLimit = `-- name: CreateAccountLimit :one
INSERT INTO provider_account_limits (account_id, limit_type, window_seconds, limit_value, is_hard, cooldown_seconds)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, limit_type, window_seconds, limit_value, is_hard, cooldown_seconds, created_at
`

type CreateAccountLimitParams struct {
	AccountID       uuid.UUID      `json:"account_id"`
	LimitType       string         `json:"limit_type"`
	WindowSeconds   int32          `json:"window_seconds"`
	LimitValue      pgtype.Numeric `json:"limit_value"`
	IsHard          *bool          `json:"is_hard"`
	CooldownSeconds *int32         `json:"cooldown_seconds"`
}

func (q *Queries) CreateAccountLimit(ctx context.Context, arg CreateAccountLimitParams) (ProviderAccountLimit, error) {
	row := q.db.QueryRow(ctx, createAccountLimit,
		arg.AccountID,
		arg.LimitType,
		arg.WindowSeconds,
		arg.LimitValue,
		arg.IsHard,
		arg.CooldownSeconds,
	)
	var i ProviderAccountLimit
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.LimitType,
		&i.WindowSeconds,
		&i.LimitValue,
		&i.IsHard,
		&i.CooldownSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const createModelEndpoint = `-- name: CreateModelEndpoint :one
INSERT INTO model_endpoints (
    account_id, model_id, transport, upstream_route, base_url,
    pricing_basis, unit_price_input, unit_price_output,
    latency_estimate_ms, throughput_tps, priority, quality_tier
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, account_id, model_id, transport, upstream_route, base_url, pricing_basis, unit_price_input, unit_price_output, latency_estimate_ms, throughput_tps, priority, quality_tier, status, cooldown_until, created_at, updated_at
`

type CreateModelEndpointParams struct {
	AccountID         uuid.UUID      `json:"account_id"`
	ModelID           uuid.UUID      `json:"model_id"`
	Transport         string         `json:"transport"`
	UpstreamRoute     *string        `json:"upstream_route"`
	BaseUrl           *string        `json:"base_url"`
	PricingBasis      *string        `json:"pricing_basis"`
	UnitPriceInput    pgtype.Numeric `json:"unit_price_input"`
	UnitPriceOutput   pgtype.Numeric `json:"unit_price_output"`
	LatencyEstimateMs *int32         `json:"latency_estimate_ms"`
	ThroughputTps     pgtype.Numeric `json:"throughput_tps"`
	Priority          *int32         `json:"priority"`
	QualityTier       *string        `json:"quality_tier"`
}

func (q *Queries) CreateModelEndpoint(ctx context.Context, arg CreateModelEndpointParams) (ModelEndpoint, error) {
	row := q.db.QueryRow(ctx, createModelEndpoint,
		arg.AccountID,
		arg.ModelID,
		arg.Transport,
		arg.UpstreamRoute,
		arg.BaseUrl,
		arg.PricingBasis,
		arg.UnitPriceInput,
		arg.UnitPriceOutput,
		arg.LatencyEstimateMs,
		arg.ThroughputTps,
		arg.Priority,
		arg.QualityTier,
	)
	var i ModelEndpoint
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ModelID,
		&i.Transport,
		&i.UpstreamRoute,
		&i.BaseUrl,
		&i.PricingBasis,
		&i.UnitPriceInput,
		&i.UnitPriceOutput,
		&i.LatencyEstimateMs,
		&i.ThroughputTps,
		&i.Priority,
		&i.QualityTier,
		&i.Status,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProviderAccount = `-- name: CreateProviderAccount :one
INSERT INTO provider_accounts (name, backend_type, billing_model, base_currency, subscription_fee_monthly, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, backend_type, billing_model, base_currency, subscription_fee_monthly, is_active, notes, created_at, updated_at
`

type CreateProviderAccountParams struct {
	Name                   string         `json:"name"`
	BackendType            string         `json:"backend_type"`
	BillingModel           string         `json:"billing_model"`
	BaseCurrency           *string        `json:"base_currency"`
	SubscriptionFeeMonthly pgtype.Numeric `json:"subscription_fee_monthly"`
	Notes                  *string        `json:"notes"`
}

func (q *Queries) CreateProviderAccount(ctx context.Context, arg CreateProviderAccountParams) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, createProviderAccount,
		arg.Name,
		arg.BackendType,
		arg.BillingModel,
		arg.BaseCurrency,
		arg.SubscriptionFeeMonthly,
		arg.Notes,
	)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BackendType,
		&i.BillingModel,
		&i.BaseCurrency,
		&i.SubscriptionFeeMonthly,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccountLimits = `-- name: DeleteAccountLimits :exec
DELETE FROM provider_account_limits WHERE account_id = $1
`

func (q *Queries) DeleteAccountLimits(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountLimits, accountID)
	return err
}

const getAccountLimits = `-- name: GetAccountLimits :many
SELECT id, account_id, limit_type, window_seconds, limit_value, is_hard, cooldown_seconds, created_at FROM provider_account_limits WHERE account_id = $1
`

func (q *Queries) GetAccountLimits(ctx context.Context, accountID uuid.UUID) ([]ProviderAccountLimit, error) {
	rows, err := q.db.Query(ctx, getAccountLimits, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderAccountLimit{}
	for rows.Next() {
		var i ProviderAccountLimit
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.LimitType,
			&i.WindowSeconds,
			&i.LimitValue,
			&i.IsHard,
			&i.CooldownSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveEndpoints = `-- name: GetActiveEndpoints :many
SELECT me.id, me.account_id, me.model_id, me.transport, me.upstream_route, me.base_url, me.pricing_basis, me.unit_price_input, me.unit_price_output, me.latency_estimate_ms, me.throughput_tps, me.priority, me.quality_tier, me.status, me.cooldown_until, me.created_at, me.updated_at, m.model_name, m.provider, pa.name as account_name, pa.billing_model
FROM model_endpoints me
JOIN models m ON me.model_id = m.id
JOIN provider_accounts pa ON me.account_id = pa.id
WHERE me.status = 'active' AND pa.is_active = true
ORDER BY me.priority DESC
`

type GetActiveEndpointsRow struct {
	ID                uuid.UUID          `json:"id"`
	AccountID         uuid.UUID          `json:"account_id"`
	ModelID           uuid.UUID          `json:"model_id"`
	Transport         string             `json:"transport"`
	UpstreamRoute     *string            `json:"upstream_route"`
	BaseUrl           *string            `json:"base_url"`
	PricingBasis      *string            `json:"pricing_basis"`
	UnitPriceInput    pgtype.Numeric     `json:"unit_price_input"`
	UnitPriceOutput   pgtype.Numeric     `json:"unit_price_output"`
	LatencyEstimateMs *int32             `json:"latency_estimate_ms"`
	ThroughputTps     pgtype.Numeric     `json:"throughput_tps"`
	Priority          *int32             `json:"priority"`
	QualityTier       *string            `json:"quality_tier"`
	Status            *string            `json:"status"`
	CooldownUntil     pgtype.Timestamptz `json:"cooldown_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ModelName         string             `json:"model_name"`
	Provider          string             `json:"provider"`
	AccountName       string             `json:"account_name"`
	BillingModel      string             `json:"billing_model"`
}

func (q *Queries) GetActiveEndpoints(ctx context.Context) ([]GetActiveEndpointsRow, error) {
	rows, err := q.db.Query(ctx, getActiveEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveEndpointsRow{}
	for rows.Next() {
		var i GetActiveEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ModelID,
			&i.Transport,
			&i.UpstreamRoute,
			&i.BaseUrl,
			&i.PricingBasis,
			&i.UnitPriceInput,
			&i.UnitPriceOutput,
			&i.LatencyEstimateMs,
			&i.ThroughputTps,
			&i.Priority,
			&i.QualityTier,
			&i.Status,
			&i.CooldownUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelName,
			&i.Provider,
			&i.AccountName,
			&i.BillingModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentUsage = `-- name: GetCurrentUsage :one
SELECT id, account_id, endpoint_id, window_type, window_start, window_end, tokens_in, tokens_out, requests, credits_used, cost_usd, percent_remaining, last_refreshed_at, created_at FROM account_usage_snapshots 
WHERE account_id = $1 AND window_type = $2 AND window_start <= $3 AND window_end > $3
ORDER BY window_start DESC
LIMIT 1
`

type GetCurrentUsageParams struct {
	AccountID   uuid.UUID          `json:"account_id"`
	WindowType  string             `json:"window_type"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
}

func (q *Queries) GetCurrentUsage(ctx context.Context, arg GetCurrentUsageParams) (AccountUsageSnapshot, error) {
	row := q.db.QueryRow(ctx, getCurrentUsage, arg.AccountID, arg.WindowType, arg.WindowStart)
	var i AccountUsageSnapshot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EndpointID,
		&i.WindowType,
		&i.WindowStart,
		&i.WindowEnd,
		&i.TokensIn,
		&i.TokensOut,
		&i.Requests,
		&i.CreditsUsed,
		&i.CostUsd,
		&i.PercentRemaining,
		&i.LastRefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEndpointHealth = `-- name: GetEndpointHealth :one
SELECT id, endpoint_id, consecutive_failures, consecutive_successes, last_success_at, last_failure_at, last_error, avg_latency_ms, p95_latency_ms, success_rate, is_healthy, health_check_at FROM endpoint_health WHERE endpoint_id = $1
`

func (q *Queries) GetEndpointHealth(ctx context.Context, endpointID uuid.UUID) (EndpointHealth, error) {
	row := q.db.QueryRow(ctx, getEndpointHealth, endpointID)
	var i EndpointHealth
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
		&i.AvgLatencyMs,
		&i.P95LatencyMs,
		&i.SuccessRate,
		&i.IsHealthy,
		&i.HealthCheckAt,
	)
	return i, err
}

const getEndpointsForAccount = `-- name: GetEndpointsForAccount :many
SELECT me.id, me.account_id, me.model_id, me.transport, me.upstream_route, me.base_url, me.pricing_basis, me.unit_price_input, me.unit_price_output, me.latency_estimate_ms, me.throughput_tps, me.priority, me.quality_tier, me.status, me.cooldown_until, me.created_at, me.updated_at, m.model_name, m.provider
FROM model_endpoints me
JOIN models m ON me.model_id = m.id
WHERE me.account_id = $1
ORDER BY me.priority DESC
`

type GetEndpointsForAccountRow struct {
	ID                uuid.UUID          `json:"id"`
	AccountID         uuid.UUID          `json:"account_id"`
	ModelID           uuid.UUID          `json:"model_id"`
	Transport         string             `json:"transport"`
	UpstreamRoute     *string            `json:"upstream_route"`
	BaseUrl           *string            `json:"base_url"`
	PricingBasis      *string            `json:"pricing_basis"`
	UnitPriceInput    pgtype.Numeric     `json:"unit_price_input"`
	UnitPriceOutput   pgtype.Numeric     `json:"unit_price_output"`
	LatencyEstimateMs *int32             `json:"latency_estimate_ms"`
	ThroughputTps     pgtype.Numeric     `json:"throughput_tps"`
	Priority          *int32             `json:"priority"`
	QualityTier       *string            `json:"quality_tier"`
	Status            *string            `json:"status"`
	CooldownUntil     pgtype.Timestamptz `json:"cooldown_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ModelName         string             `json:"model_name"`
	Provider          string             `json:"provider"`
}

func (q *Queries) GetEndpointsForAccount(ctx context.Context, accountID uuid.UUID) ([]GetEndpointsForAccountRow, error) {
	rows, err := q.db.Query(ctx, getEndpointsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEndpointsForAccountRow{}
	for rows.Next() {
		var i GetEndpointsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ModelID,
			&i.Transport,
			&i.UpstreamRoute,
			&i.BaseUrl,
			&i.PricingBasis,
			&i.UnitPriceInput,
			&i.UnitPriceOutput,
			&i.LatencyEstimateMs,
			&i.ThroughputTps,
			&i.Priority,
			&i.QualityTier,
			&i.Status,
			&i.CooldownUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelName,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEndpointsForModel = `-- name: GetEndpointsForModel :many
SELECT me.id, me.account_id, me.model_id, me.transport, me.upstream_route, me.base_url, me.pricing_basis, me.unit_price_input, me.unit_price_output, me.latency_estimate_ms, me.throughput_tps, me.priority, me.quality_tier, me.status, me.cooldown_until, me.created_at, me.updated_at, pa.name as account_name, pa.billing_model, pa.is_active as account_active
FROM model_endpoints me
JOIN provider_accounts pa ON me.account_id = pa.id
WHERE me.model_id = $1 AND me.status = 'active' AND pa.is_active = true
ORDER BY me.priority DESC, me.latency_estimate_ms ASC
`

type GetEndpointsForModelRow struct {
	ID                uuid.UUID          `json:"id"`
	AccountID         uuid.UUID          `json:"account_id"`
	ModelID           uuid.UUID          `json:"model_id"`
	Transport         string             `json:"transport"`
	UpstreamRoute     *string            `json:"upstream_route"`
	BaseUrl           *string            `json:"base_url"`
	PricingBasis      *string            `json:"pricing_basis"`
	UnitPriceInput    pgtype.Numeric     `json:"unit_price_input"`
	UnitPriceOutput   pgtype.Numeric     `json:"unit_price_output"`
	LatencyEstimateMs *int32             `json:"latency_estimate_ms"`
	ThroughputTps     pgtype.Numeric     `json:"throughput_tps"`
	Priority          *int32             `json:"priority"`
	QualityTier       *string            `json:"quality_tier"`
	Status            *string            `json:"status"`
	CooldownUntil     pgtype.Timestamptz `json:"cooldown_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AccountName       string             `json:"account_name"`
	BillingModel      string             `json:"billing_model"`
	AccountActive     *bool              `json:"account_active"`
}

func (q *Queries) GetEndpointsForModel(ctx context.Context, modelID uuid.UUID) ([]GetEndpointsForModelRow, error) {
	rows, err := q.db.Query(ctx, getEndpointsForModel, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEndpointsForModelRow{}
	for rows.Next() {
		var i GetEndpointsForModelRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ModelID,
			&i.Transport,
			&i.UpstreamRoute,
			&i.BaseUrl,
			&i.PricingBasis,
			&i.UnitPriceInput,
			&i.UnitPriceOutput,
			&i.LatencyEstimateMs,
			&i.ThroughputTps,
			&i.Priority,
			&i.QualityTier,
			&i.Status,
			&i.CooldownUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
			&i.BillingModel,
			&i.AccountActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelEndpoint = `-- name: GetModelEndpoint :one
SELECT id, account_id, model_id, transport, upstream_route, base_url, pricing_basis, unit_price_input, unit_price_output, latency_estimate_ms, throughput_tps, priority, quality_tier, status, cooldown_until, created_at, updated_at FROM model_endpoints WHERE id = $1
`

func (q *Queries) GetModelEndpoint(ctx context.Context, id uuid.UUID) (ModelEndpoint, error) {
	row := q.db.QueryRow(ctx, getModelEndpoint, id)
	var i ModelEndpoint
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ModelID,
		&i.Transport,
		&i.UpstreamRoute,
		&i.BaseUrl,
		&i.PricingBasis,
		&i.UnitPriceInput,
		&i.UnitPriceOutput,
		&i.LatencyEstimateMs,
		&i.ThroughputTps,
		&i.Priority,
		&i.QualityTier,
		&i.Status,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderAccount = `-- name: GetProviderAccount :one
SELECT id, name, backend_type, billing_model, base_currency, subscription_fee_monthly, is_active, notes, created_at, updated_at FROM provider_accounts WHERE id = $1
`

func (q *Queries) GetProviderAccount(ctx context.Context, id uuid.UUID) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, getProviderAccount, id)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BackendType,
		&i.BillingModel,
		&i.BaseCurrency,
		&i.SubscriptionFeeMonthly,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderAccountByName = `-- name: GetProviderAccountByName :one
SELECT id, name, backend_type, billing_model, base_currency, subscription_fee_monthly, is_active, notes, created_at, updated_at FROM provider_accounts WHERE name = $1
`

func (q *Queries) GetProviderAccountByName(ctx context.Context, name string) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, getProviderAccountByName, name)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BackendType,
		&i.BillingModel,
		&i.BaseCurrency,
		&i.SubscriptionFeeMonthly,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnhealthyEndpoints = `-- name: GetUnhealthyEndpoints :many
SELECT eh.id, eh.endpoint_id, eh.consecutive_failures, eh.consecutive_successes, eh.last_success_at, eh.last_failure_at, eh.last_error, eh.avg_latency_ms, eh.p95_latency_ms, eh.success_rate, eh.is_healthy, eh.health_check_at, me.model_id, me.transport
FROM endpoint_health eh
JOIN model_endpoints me ON eh.endpoint_id = me.id
WHERE eh.is_healthy = false
`

type GetUnhealthyEndpointsRow struct {
	ID                   uuid.UUID          `json:"id"`
	EndpointID           uuid.UUID          `json:"endpoint_id"`
	ConsecutiveFailures  *int32             `json:"consecutive_failures"`
	ConsecutiveSuccesses *int32             `json:"consecutive_successes"`
	LastSuccessAt        pgtype.Timestamptz `json:"last_success_at"`
	LastFailureAt        pgtype.Timestamptz `json:"last_failure_at"`
	LastError            *string            `json:"last_error"`
	AvgLatencyMs         *int32             `json:"avg_latency_ms"`
	P95LatencyMs         *int32             `json:"p95_latency_ms"`
	SuccessRate          pgtype.Numeric     `json:"success_rate"`
	IsHealthy            *bool              `json:"is_healthy"`
	HealthCheckAt        pgtype.Timestamptz `json:"health_check_at"`
	ModelID              uuid.UUID          `json:"model_id"`
	Transport            string             `json:"transport"`
}

func (q *Queries) GetUnhealthyEndpoints(ctx context.Context) ([]GetUnhealthyEndpointsRow, error) {
	rows, err := q.db.Query(ctx, getUnhealthyEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnhealthyEndpointsRow{}
	for rows.Next() {
		var i GetUnhealthyEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.ConsecutiveFailures,
			&i.ConsecutiveSuccesses,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.LastError,
			&i.AvgLatencyMs,
			&i.P95LatencyMs,
			&i.SuccessRate,
			&i.IsHealthy,
			&i.HealthCheckAt,
			&i.ModelID,
			&i.Transport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageForWindow = `-- name: GetUsageForWindow :many
SELECT id, account_id, endpoint_id, window_type, window_start, window_end, tokens_in, tokens_out, requests, credits_used, cost_usd, percent_remaining, last_refreshed_at, created_at FROM account_usage_snapshots
WHERE account_id = $1 AND window_type = $2 AND window_start >= $3 AND window_end <= $4
ORDER BY window_start
`

type GetUsageForWindowParams struct {
	AccountID   uuid.UUID          `json:"account_id"`
	WindowType  string             `json:"window_type"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
}

func (q *Queries) GetUsageForWindow(ctx context.Context, arg GetUsageForWindowParams) ([]AccountUsageSnapshot, error) {
	rows, err := q.db.Query(ctx, getUsageForWindow,
		arg.AccountID,
		arg.WindowType,
		arg.WindowStart,
		arg.WindowEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountUsageSnapshot{}
	for rows.Next() {
		var i AccountUsageSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.EndpointID,
			&i.WindowType,
			&i.WindowStart,
			&i.WindowEnd,
			&i.TokensIn,
			&i.TokensOut,
			&i.Requests,
			&i.CreditsUsed,
			&i.CostUsd,
			&i.PercentRemaining,
			&i.LastRefreshedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProviderAccounts = `-- name: ListActiveProviderAccounts :many
SELECT id, name, backend_type, billing_model, base_currency, subscription_fee_monthly, is_active, notes, created_at, updated_at FROM provider_accounts WHERE is_active = true ORDER BY name
`

func (q *Queries) ListActiveProviderAccounts(ctx context.Context) ([]ProviderAccount, error) {
	rows, err := q.db.Query(ctx, listActiveProviderAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderAccount{}
	for rows.Next() {
		var i ProviderAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BackendType,
			&i.BillingModel,
			&i.BaseCurrency,
			&i.SubscriptionFeeMonthly,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEndpointFailure = `-- name: RecordEndpointFailure :exec
UPDATE endpoint_health SET
    consecutive_failures = consecutive_failures + 1,
    consecutive_successes = 0,
    last_failure_at = NOW(),
    last_error = $2,
    is_healthy = CASE WHEN consecutive_failures >= 3 THEN false ELSE is_healthy END,
    health_check_at = NOW()
WHERE endpoint_id = $1
`

type RecordEndpointFailureParams struct {
	EndpointID uuid.UUID `json:"endpoint_id"`
	LastError  *string   `json:"last_error"`
}

func (q *Queries) RecordEndpointFailure(ctx context.Context, arg RecordEndpointFailureParams) error {
	_, err := q.db.Exec(ctx, recordEndpointFailure, arg.EndpointID, arg.LastError)
	return err
}

const recordEndpointSuccess = `-- name: RecordEndpointSuccess :exec
UPDATE endpoint_health SET
    consecutive_successes = consecutive_successes + 1,
    consecutive_failures = 0,
    last_success_at = NOW(),
    is_healthy = true,
    health_check_at = NOW()
WHERE endpoint_id = $1
`

func (q *Queries) RecordEndpointSuccess(ctx context.Context, endpointID uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordEndpointSuccess, endpointID)
	return err
}

const setEndpointCooldown = `-- name: SetEndpointCooldown :exec
UPDATE model_endpoints 
SET status = 'cooldown', cooldown_until = $2, updated_at = NOW() 
WHERE id = $1
`

type SetEndpointCooldownParams struct {
	ID            uuid.UUID          `json:"id"`
	CooldownUntil pgtype.Timestamptz `json:"cooldown_until"`
}

func (q *Queries) SetEndpointCooldown(ctx context.Context, arg SetEndpointCooldownParams) error {
	_, err := q.db.Exec(ctx, setEndpointCooldown, arg.ID, arg.CooldownUntil)
	return err
}

const updateEndpointStatus = `-- name: UpdateEndpointStatus :exec
UPDATE model_endpoints SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateEndpointStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status *string   `json:"status"`
}

func (q *Queries) UpdateEndpointStatus(ctx context.Context, arg UpdateEndpointStatusParams) error {
	_, err := q.db.Exec(ctx, updateEndpointStatus, arg.ID, arg.Status)
	return err
}

const updateProviderAccountStatus = `-- name: UpdateProviderAccountStatus :exec
UPDATE provider_accounts SET is_active = $2, updated_at = NOW() WHERE id = $1
`

type UpdateProviderAccountStatusParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive *bool     `json:"is_active"`
}

func (q *Queries) UpdateProviderAccountStatus(ctx context.Context, arg UpdateProviderAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateProviderAccountStatus, arg.ID, arg.IsActive)
	return err
}

const upsertEndpointHealth = `-- name: UpsertEndpointHealth :one
INSERT INTO endpoint_health (endpoint_id, is_healthy)
VALUES ($1, true)
ON CONFLICT (endpoint_id)
DO UPDATE SET health_check_at = NOW()
RETURNING id, endpoint_id, consecutive_failures, consecutive_successes, last_success_at, last_failure_at, last_error, avg_latency_ms, p95_latency_ms, success_rate, is_healthy, health_check_at
`

func (q *Queries) UpsertEndpointHealth(ctx context.Context, endpointID uuid.UUID) (EndpointHealth, error) {
	row := q.db.QueryRow(ctx, upsertEndpointHealth, endpointID)
	var i EndpointHealth
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastError,
		&i.AvgLatencyMs,
		&i.P95LatencyMs,
		&i.SuccessRate,
		&i.IsHealthy,
		&i.HealthCheckAt,
	)
	return i, err
}

const upsertUsageSnapshot = `-- name: UpsertUsageSnapshot :one
INSERT INTO account_usage_snapshots (
    account_id, endpoint_id, window_type, window_start, window_end,
    tokens_in, tokens_out, requests, credits_used, cost_usd
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (account_id, endpoint_id, window_type, window_start)
DO UPDATE SET
    tokens_in = account_usage_snapshots.tokens_in + EXCLUDED.tokens_in,
    tokens_out = account_usage_snapshots.tokens_out + EXCLUDED.tokens_out,
    requests = account_usage_snapshots.requests + EXCLUDED.requests,
    credits_used = account_usage_snapshots.credits_used + EXCLUDED.credits_used,
    cost_usd = account_usage_snapshots.cost_usd + EXCLUDED.cost_usd,
    last_refreshed_at = NOW()
RETURNING id, account_id, endpoint_id, window_type, window_start, window_end, tokens_in, tokens_out, requests, credits_used, cost_usd, percent_remaining, last_refreshed_at, created_at
`

type UpsertUsageSnapshotParams struct {
	AccountID   uuid.UUID          `json:"account_id"`
	EndpointID  pgtype.UUID        `json:"endpoint_id"`
	WindowType  string             `json:"window_type"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	TokensIn    *int64             `json:"tokens_in"`
	TokensOut   *int64             `json:"tokens_out"`
	Requests    *int32             `json:"requests"`
	CreditsUsed pgtype.Numeric     `json:"credits_used"`
	CostUsd     pgtype.Numeric     `json:"cost_usd"`
}

func (q *Queries) UpsertUsageSnapshot(ctx context.Context, arg UpsertUsageSnapshotParams) (AccountUsageSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertUsageSnapshot,
		arg.AccountID,
		arg.EndpointID,
		arg.WindowType,
		arg.WindowStart,
		arg.WindowEnd,
		arg.TokensIn,
		arg.TokensOut,
		arg.Requests,
		arg.CreditsUsed,
		arg.CostUsd,
	)
	var i AccountUsageSnapshot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EndpointID,
		&i.WindowType,
		&i.WindowStart,
		&i.WindowEnd,
		&i.TokensIn,
		&i.TokensOut,
		&i.Requests,
		&i.CreditsUsed,
		&i.CostUsd,
		&i.PercentRemaining,
		&i.LastRefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}
