// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bandits.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decayBanditPriors = `-- name: DecayBanditPriors :exec
UPDATE bandit_state SET
    alpha = 1.0 + (alpha - 1.0) * $1,  -- decay factor (e.g., 0.99)
    beta = 1.0 + (beta - 1.0) * $1,
    last_updated = NOW()
WHERE last_updated < NOW() - INTERVAL '1 day'
`

// Apply decay to move priors toward uncertainty (for exploration)
// Typically run nightly to prevent stale beliefs
func (q *Queries) DecayBanditPriors(ctx context.Context, alpha pgtype.Numeric) error {
	_, err := q.db.Exec(ctx, decayBanditPriors, alpha)
	return err
}

const getAllBanditStates = `-- name: GetAllBanditStates :many
SELECT 
    bs.id, bs.model_id, bs.role_id, bs.alpha, bs.beta, bs.total_trials, bs.last_updated,
    m.provider,
    m.model_name,
    r.name AS role_name
FROM bandit_state bs
JOIN models m ON m.id = bs.model_id
LEFT JOIN roles r ON r.id = bs.role_id
ORDER BY bs.model_id, bs.role_id
`

type GetAllBanditStatesRow struct {
	ID          uuid.UUID          `json:"id"`
	ModelID     uuid.UUID          `json:"model_id"`
	RoleID      pgtype.UUID        `json:"role_id"`
	Alpha       pgtype.Numeric     `json:"alpha"`
	Beta        pgtype.Numeric     `json:"beta"`
	TotalTrials *int32             `json:"total_trials"`
	LastUpdated pgtype.Timestamptz `json:"last_updated"`
	Provider    string             `json:"provider"`
	ModelName   string             `json:"model_name"`
	RoleName    *string            `json:"role_name"`
}

func (q *Queries) GetAllBanditStates(ctx context.Context) ([]GetAllBanditStatesRow, error) {
	rows, err := q.db.Query(ctx, getAllBanditStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllBanditStatesRow{}
	for rows.Next() {
		var i GetAllBanditStatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.RoleID,
			&i.Alpha,
			&i.Beta,
			&i.TotalTrials,
			&i.LastUpdated,
			&i.Provider,
			&i.ModelName,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBanditState = `-- name: GetBanditState :one

SELECT id, model_id, role_id, alpha, beta, total_trials, last_updated FROM bandit_state 
WHERE model_id = $1 
  AND (role_id = $2 OR ($2 IS NULL AND role_id IS NULL))
`

type GetBanditStateParams struct {
	ModelID uuid.UUID   `json:"model_id"`
	RoleID  pgtype.UUID `json:"role_id"`
}

// Bandit queries for Thompson Sampling exploration
func (q *Queries) GetBanditState(ctx context.Context, arg GetBanditStateParams) (BanditState, error) {
	row := q.db.QueryRow(ctx, getBanditState, arg.ModelID, arg.RoleID)
	var i BanditState
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.RoleID,
		&i.Alpha,
		&i.Beta,
		&i.TotalTrials,
		&i.LastUpdated,
	)
	return i, err
}

const getBanditStatesForRole = `-- name: GetBanditStatesForRole :many
SELECT 
    bs.id, bs.model_id, bs.role_id, bs.alpha, bs.beta, bs.total_trials, bs.last_updated,
    m.provider,
    m.model_name,
    bs.alpha / (bs.alpha + bs.beta) AS mean_reward,
    bs.alpha + bs.beta AS total_observations
FROM bandit_state bs
JOIN models m ON m.id = bs.model_id
WHERE bs.role_id = $1 OR ($1 IS NULL AND bs.role_id IS NULL)
ORDER BY mean_reward DESC
`

type GetBanditStatesForRoleRow struct {
	ID                uuid.UUID          `json:"id"`
	ModelID           uuid.UUID          `json:"model_id"`
	RoleID            pgtype.UUID        `json:"role_id"`
	Alpha             pgtype.Numeric     `json:"alpha"`
	Beta              pgtype.Numeric     `json:"beta"`
	TotalTrials       *int32             `json:"total_trials"`
	LastUpdated       pgtype.Timestamptz `json:"last_updated"`
	Provider          string             `json:"provider"`
	ModelName         string             `json:"model_name"`
	MeanReward        int32              `json:"mean_reward"`
	TotalObservations int32              `json:"total_observations"`
}

func (q *Queries) GetBanditStatesForRole(ctx context.Context, roleID pgtype.UUID) ([]GetBanditStatesForRoleRow, error) {
	rows, err := q.db.Query(ctx, getBanditStatesForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBanditStatesForRoleRow{}
	for rows.Next() {
		var i GetBanditStatesForRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.RoleID,
			&i.Alpha,
			&i.Beta,
			&i.TotalTrials,
			&i.LastUpdated,
			&i.Provider,
			&i.ModelName,
			&i.MeanReward,
			&i.TotalObservations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExplorationCandidates = `-- name: GetExplorationCandidates :many
SELECT 
    bs.id, bs.model_id, bs.role_id, bs.alpha, bs.beta, bs.total_trials, bs.last_updated,
    m.provider,
    m.model_name,
    m.status,
    -- Uncertainty = variance of Beta distribution
    (bs.alpha * bs.beta) / (POWER(bs.alpha + bs.beta, 2) * (bs.alpha + bs.beta + 1)) AS uncertainty
FROM bandit_state bs
JOIN models m ON m.id = bs.model_id
WHERE m.status IN ('active', 'shadow')
  AND bs.total_trials < $1  -- min trials threshold
ORDER BY uncertainty DESC
LIMIT $2
`

type GetExplorationCandidatesParams struct {
	TotalTrials *int32 `json:"total_trials"`
	Limit       int32  `json:"limit"`
}

type GetExplorationCandidatesRow struct {
	ID          uuid.UUID          `json:"id"`
	ModelID     uuid.UUID          `json:"model_id"`
	RoleID      pgtype.UUID        `json:"role_id"`
	Alpha       pgtype.Numeric     `json:"alpha"`
	Beta        pgtype.Numeric     `json:"beta"`
	TotalTrials *int32             `json:"total_trials"`
	LastUpdated pgtype.Timestamptz `json:"last_updated"`
	Provider    string             `json:"provider"`
	ModelName   string             `json:"model_name"`
	Status      string             `json:"status"`
	Uncertainty int32              `json:"uncertainty"`
}

// Get models that need exploration (high uncertainty)
func (q *Queries) GetExplorationCandidates(ctx context.Context, arg GetExplorationCandidatesParams) ([]GetExplorationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, getExplorationCandidates, arg.TotalTrials, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExplorationCandidatesRow{}
	for rows.Next() {
		var i GetExplorationCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.RoleID,
			&i.Alpha,
			&i.Beta,
			&i.TotalTrials,
			&i.LastUpdated,
			&i.Provider,
			&i.ModelName,
			&i.Status,
			&i.Uncertainty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementBanditFailure = `-- name: IncrementBanditFailure :exec
UPDATE bandit_state SET
    beta = beta + 1,
    total_trials = total_trials + 1,
    last_updated = NOW()
WHERE model_id = $1 
  AND (role_id = $2 OR ($2 IS NULL AND role_id IS NULL))
`

type IncrementBanditFailureParams struct {
	ModelID uuid.UUID   `json:"model_id"`
	RoleID  pgtype.UUID `json:"role_id"`
}

// Increment beta (failure count) for Thompson Sampling
func (q *Queries) IncrementBanditFailure(ctx context.Context, arg IncrementBanditFailureParams) error {
	_, err := q.db.Exec(ctx, incrementBanditFailure, arg.ModelID, arg.RoleID)
	return err
}

const incrementBanditSuccess = `-- name: IncrementBanditSuccess :exec
UPDATE bandit_state SET
    alpha = alpha + 1,
    total_trials = total_trials + 1,
    last_updated = NOW()
WHERE model_id = $1 
  AND (role_id = $2 OR ($2 IS NULL AND role_id IS NULL))
`

type IncrementBanditSuccessParams struct {
	ModelID uuid.UUID   `json:"model_id"`
	RoleID  pgtype.UUID `json:"role_id"`
}

// Increment alpha (success count) for Thompson Sampling
func (q *Queries) IncrementBanditSuccess(ctx context.Context, arg IncrementBanditSuccessParams) error {
	_, err := q.db.Exec(ctx, incrementBanditSuccess, arg.ModelID, arg.RoleID)
	return err
}

const initializeBanditForModel = `-- name: InitializeBanditForModel :exec
INSERT INTO bandit_state (model_id, role_id, alpha, beta, total_trials)
SELECT $1, r.id, 1.0, 1.0, 0
FROM roles r
ON CONFLICT (model_id, role_id) DO NOTHING
`

// Initialize bandit state for a new model across all roles
func (q *Queries) InitializeBanditForModel(ctx context.Context, modelID uuid.UUID) error {
	_, err := q.db.Exec(ctx, initializeBanditForModel, modelID)
	return err
}

const upsertBanditState = `-- name: UpsertBanditState :one
INSERT INTO bandit_state (model_id, role_id, alpha, beta, total_trials)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (model_id, role_id) DO UPDATE SET
    alpha = EXCLUDED.alpha,
    beta = EXCLUDED.beta,
    total_trials = EXCLUDED.total_trials,
    last_updated = NOW()
RETURNING id, model_id, role_id, alpha, beta, total_trials, last_updated
`

type UpsertBanditStateParams struct {
	ModelID     uuid.UUID      `json:"model_id"`
	RoleID      pgtype.UUID    `json:"role_id"`
	Alpha       pgtype.Numeric `json:"alpha"`
	Beta        pgtype.Numeric `json:"beta"`
	TotalTrials *int32         `json:"total_trials"`
}

func (q *Queries) UpsertBanditState(ctx context.Context, arg UpsertBanditStateParams) (BanditState, error) {
	row := q.db.QueryRow(ctx, upsertBanditState,
		arg.ModelID,
		arg.RoleID,
		arg.Alpha,
		arg.Beta,
		arg.TotalTrials,
	)
	var i BanditState
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.RoleID,
		&i.Alpha,
		&i.Beta,
		&i.TotalTrials,
		&i.LastUpdated,
	)
	return i, err
}
