// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: context.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createConversationSegment = `-- name: CreateConversationSegment :one
INSERT INTO conversation_segments (
    conversation_id, segment_index, role, content,
    token_count, summary, summary_token_count, embedding
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, conversation_id, segment_index, role, content, token_count, summary, summary_token_count, embedding, created_at, raw_storage_key, short_summary, importance, session_id
`

type CreateConversationSegmentParams struct {
	ConversationID    uuid.UUID        `json:"conversation_id"`
	SegmentIndex      int32            `json:"segment_index"`
	Role              string           `json:"role"`
	Content           string           `json:"content"`
	TokenCount        *int32           `json:"token_count"`
	Summary           *string          `json:"summary"`
	SummaryTokenCount *int32           `json:"summary_token_count"`
	Embedding         *pgvector.Vector `json:"embedding"`
}

func (q *Queries) CreateConversationSegment(ctx context.Context, arg CreateConversationSegmentParams) (ConversationSegment, error) {
	row := q.db.QueryRow(ctx, createConversationSegment,
		arg.ConversationID,
		arg.SegmentIndex,
		arg.Role,
		arg.Content,
		arg.TokenCount,
		arg.Summary,
		arg.SummaryTokenCount,
		arg.Embedding,
	)
	var i ConversationSegment
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SegmentIndex,
		&i.Role,
		&i.Content,
		&i.TokenCount,
		&i.Summary,
		&i.SummaryTokenCount,
		&i.Embedding,
		&i.CreatedAt,
		&i.RawStorageKey,
		&i.ShortSummary,
		&i.Importance,
		&i.SessionID,
	)
	return i, err
}

const createDocumentChunk = `-- name: CreateDocumentChunk :one
INSERT INTO document_chunks (
    document_id, chunk_index, content, token_count, embedding, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, document_id, chunk_index, content, token_count, embedding, metadata, created_at, doc_id, short_summary, medium_summary, importance
`

type CreateDocumentChunkParams struct {
	DocumentID uuid.UUID        `json:"document_id"`
	ChunkIndex int32            `json:"chunk_index"`
	Content    string           `json:"content"`
	TokenCount *int32           `json:"token_count"`
	Embedding  *pgvector.Vector `json:"embedding"`
	Metadata   []byte           `json:"metadata"`
}

func (q *Queries) CreateDocumentChunk(ctx context.Context, arg CreateDocumentChunkParams) (DocumentChunk, error) {
	row := q.db.QueryRow(ctx, createDocumentChunk,
		arg.DocumentID,
		arg.ChunkIndex,
		arg.Content,
		arg.TokenCount,
		arg.Embedding,
		arg.Metadata,
	)
	var i DocumentChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ChunkIndex,
		&i.Content,
		&i.TokenCount,
		&i.Embedding,
		&i.Metadata,
		&i.CreatedAt,
		&i.DocID,
		&i.ShortSummary,
		&i.MediumSummary,
		&i.Importance,
	)
	return i, err
}

const createFeedback = `-- name: CreateFeedback :one

INSERT INTO feedback (
    routing_event_id, user_id, rating, 
    feedback_type, was_regenerated, was_edited
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, routing_event_id, user_id, rating, feedback_type, was_regenerated, was_edited, created_at
`

type CreateFeedbackParams struct {
	RoutingEventID pgtype.UUID `json:"routing_event_id"`
	UserID         *string     `json:"user_id"`
	Rating         *int32      `json:"rating"`
	FeedbackType   *string     `json:"feedback_type"`
	WasRegenerated *bool       `json:"was_regenerated"`
	WasEdited      *bool       `json:"was_edited"`
}

// Feedback
func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRow(ctx, createFeedback,
		arg.RoutingEventID,
		arg.UserID,
		arg.Rating,
		arg.FeedbackType,
		arg.WasRegenerated,
		arg.WasEdited,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.RoutingEventID,
		&i.UserID,
		&i.Rating,
		&i.FeedbackType,
		&i.WasRegenerated,
		&i.WasEdited,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    name, description, parent_role_id,
    default_model_id, max_tokens, max_cost_per_request
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, description, parent_role_id, default_model_id, max_tokens, max_cost_per_request, created_at
`

type CreateRoleParams struct {
	Name              string         `json:"name"`
	Description       *string        `json:"description"`
	ParentRoleID      pgtype.UUID    `json:"parent_role_id"`
	DefaultModelID    pgtype.UUID    `json:"default_model_id"`
	MaxTokens         *int32         `json:"max_tokens"`
	MaxCostPerRequest pgtype.Numeric `json:"max_cost_per_request"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.Name,
		arg.Description,
		arg.ParentRoleID,
		arg.DefaultModelID,
		arg.MaxTokens,
		arg.MaxCostPerRequest,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentRoleID,
		&i.DefaultModelID,
		&i.MaxTokens,
		&i.MaxCostPerRequest,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldSegments = `-- name: DeleteOldSegments :exec
DELETE FROM conversation_segments
WHERE conversation_id = $1 
  AND segment_index < $2
`

type DeleteOldSegmentsParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SegmentIndex   int32     `json:"segment_index"`
}

// Clean up old conversation segments
func (q *Queries) DeleteOldSegments(ctx context.Context, arg DeleteOldSegmentsParams) error {
	_, err := q.db.Exec(ctx, deleteOldSegments, arg.ConversationID, arg.SegmentIndex)
	return err
}

const findRelevantChunks = `-- name: FindRelevantChunks :many
SELECT 
    dc.id, dc.document_id, dc.chunk_index, dc.content, dc.token_count, dc.embedding, dc.metadata, dc.created_at, dc.doc_id, dc.short_summary, dc.medium_summary, dc.importance,
    dc.embedding <-> $1 AS distance
FROM document_chunks dc
WHERE dc.document_id = ANY($2::uuid[])
ORDER BY distance
LIMIT $3
`

type FindRelevantChunksParams struct {
	Embedding *pgvector.Vector `json:"embedding"`
	Column2   []uuid.UUID      `json:"column_2"`
	Limit     int32            `json:"limit"`
}

type FindRelevantChunksRow struct {
	ID            uuid.UUID          `json:"id"`
	DocumentID    uuid.UUID          `json:"document_id"`
	ChunkIndex    int32              `json:"chunk_index"`
	Content       string             `json:"content"`
	TokenCount    *int32             `json:"token_count"`
	Embedding     *pgvector.Vector   `json:"embedding"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DocID         pgtype.UUID        `json:"doc_id"`
	ShortSummary  *string            `json:"short_summary"`
	MediumSummary *string            `json:"medium_summary"`
	Importance    pgtype.Numeric     `json:"importance"`
	Distance      interface{}        `json:"distance"`
}

// Find document chunks relevant to query
func (q *Queries) FindRelevantChunks(ctx context.Context, arg FindRelevantChunksParams) ([]FindRelevantChunksRow, error) {
	rows, err := q.db.Query(ctx, findRelevantChunks, arg.Embedding, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRelevantChunksRow{}
	for rows.Next() {
		var i FindRelevantChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.TokenCount,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.DocID,
			&i.ShortSummary,
			&i.MediumSummary,
			&i.Importance,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRelevantChunksGlobal = `-- name: FindRelevantChunksGlobal :many
SELECT 
    dc.id, dc.document_id, dc.chunk_index, dc.content, dc.token_count, dc.embedding, dc.metadata, dc.created_at, dc.doc_id, dc.short_summary, dc.medium_summary, dc.importance,
    dc.embedding <-> $1 AS distance
FROM document_chunks dc
ORDER BY distance
LIMIT $2
`

type FindRelevantChunksGlobalParams struct {
	Embedding *pgvector.Vector `json:"embedding"`
	Limit     int32            `json:"limit"`
}

type FindRelevantChunksGlobalRow struct {
	ID            uuid.UUID          `json:"id"`
	DocumentID    uuid.UUID          `json:"document_id"`
	ChunkIndex    int32              `json:"chunk_index"`
	Content       string             `json:"content"`
	TokenCount    *int32             `json:"token_count"`
	Embedding     *pgvector.Vector   `json:"embedding"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DocID         pgtype.UUID        `json:"doc_id"`
	ShortSummary  *string            `json:"short_summary"`
	MediumSummary *string            `json:"medium_summary"`
	Importance    pgtype.Numeric     `json:"importance"`
	Distance      interface{}        `json:"distance"`
}

// Find relevant chunks across all documents
func (q *Queries) FindRelevantChunksGlobal(ctx context.Context, arg FindRelevantChunksGlobalParams) ([]FindRelevantChunksGlobalRow, error) {
	rows, err := q.db.Query(ctx, findRelevantChunksGlobal, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRelevantChunksGlobalRow{}
	for rows.Next() {
		var i FindRelevantChunksGlobalRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.TokenCount,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.DocID,
			&i.ShortSummary,
			&i.MediumSummary,
			&i.Importance,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRelevantSegments = `-- name: FindRelevantSegments :many
SELECT 
    cs.id, cs.conversation_id, cs.segment_index, cs.role, cs.content, cs.token_count, cs.summary, cs.summary_token_count, cs.embedding, cs.created_at, cs.raw_storage_key, cs.short_summary, cs.importance, cs.session_id,
    cs.embedding <-> $1 AS distance
FROM conversation_segments cs
WHERE cs.conversation_id = $2
ORDER BY distance
LIMIT $3
`

type FindRelevantSegmentsParams struct {
	Embedding      *pgvector.Vector `json:"embedding"`
	ConversationID uuid.UUID        `json:"conversation_id"`
	Limit          int32            `json:"limit"`
}

type FindRelevantSegmentsRow struct {
	ID                uuid.UUID          `json:"id"`
	ConversationID    uuid.UUID          `json:"conversation_id"`
	SegmentIndex      int32              `json:"segment_index"`
	Role              string             `json:"role"`
	Content           string             `json:"content"`
	TokenCount        *int32             `json:"token_count"`
	Summary           *string            `json:"summary"`
	SummaryTokenCount *int32             `json:"summary_token_count"`
	Embedding         *pgvector.Vector   `json:"embedding"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RawStorageKey     *string            `json:"raw_storage_key"`
	ShortSummary      *string            `json:"short_summary"`
	Importance        pgtype.Numeric     `json:"importance"`
	SessionID         pgtype.UUID        `json:"session_id"`
	Distance          interface{}        `json:"distance"`
}

// Find conversation segments relevant to current query
func (q *Queries) FindRelevantSegments(ctx context.Context, arg FindRelevantSegmentsParams) ([]FindRelevantSegmentsRow, error) {
	rows, err := q.db.Query(ctx, findRelevantSegments, arg.Embedding, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRelevantSegmentsRow{}
	for rows.Next() {
		var i FindRelevantSegmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SegmentIndex,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.Summary,
			&i.SummaryTokenCount,
			&i.Embedding,
			&i.CreatedAt,
			&i.RawStorageKey,
			&i.ShortSummary,
			&i.Importance,
			&i.SessionID,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAverageRating = `-- name: GetAverageRating :one
SELECT 
    AVG(rating) AS avg_rating,
    COUNT(*) AS total_feedback
FROM feedback f
JOIN routing_events re ON re.id = f.routing_event_id
WHERE re.selected_model_id = $1
  AND f.rating IS NOT NULL
  AND f.created_at >= $2
`

type GetAverageRatingParams struct {
	SelectedModelID pgtype.UUID        `json:"selected_model_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type GetAverageRatingRow struct {
	AvgRating     float64 `json:"avg_rating"`
	TotalFeedback int64   `json:"total_feedback"`
}

func (q *Queries) GetAverageRating(ctx context.Context, arg GetAverageRatingParams) (GetAverageRatingRow, error) {
	row := q.db.QueryRow(ctx, getAverageRating, arg.SelectedModelID, arg.CreatedAt)
	var i GetAverageRatingRow
	err := row.Scan(&i.AvgRating, &i.TotalFeedback)
	return i, err
}

const getConversationSegment = `-- name: GetConversationSegment :one
SELECT id, conversation_id, segment_index, role, content, token_count, summary, summary_token_count, embedding, created_at, raw_storage_key, short_summary, importance, session_id FROM conversation_segments 
WHERE conversation_id = $1 AND segment_index = $2
`

type GetConversationSegmentParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SegmentIndex   int32     `json:"segment_index"`
}

func (q *Queries) GetConversationSegment(ctx context.Context, arg GetConversationSegmentParams) (ConversationSegment, error) {
	row := q.db.QueryRow(ctx, getConversationSegment, arg.ConversationID, arg.SegmentIndex)
	var i ConversationSegment
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SegmentIndex,
		&i.Role,
		&i.Content,
		&i.TokenCount,
		&i.Summary,
		&i.SummaryTokenCount,
		&i.Embedding,
		&i.CreatedAt,
		&i.RawStorageKey,
		&i.ShortSummary,
		&i.Importance,
		&i.SessionID,
	)
	return i, err
}

const getConversationSegments = `-- name: GetConversationSegments :many

SELECT id, conversation_id, segment_index, role, content, token_count, summary, summary_token_count, embedding, created_at, raw_storage_key, short_summary, importance, session_id FROM conversation_segments 
WHERE conversation_id = $1
ORDER BY segment_index
`

// Context folding and document queries
func (q *Queries) GetConversationSegments(ctx context.Context, conversationID uuid.UUID) ([]ConversationSegment, error) {
	rows, err := q.db.Query(ctx, getConversationSegments, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationSegment{}
	for rows.Next() {
		var i ConversationSegment
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SegmentIndex,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.Summary,
			&i.SummaryTokenCount,
			&i.Embedding,
			&i.CreatedAt,
			&i.RawStorageKey,
			&i.ShortSummary,
			&i.Importance,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationTokenCount = `-- name: GetConversationTokenCount :one
SELECT 
    SUM(token_count) AS total_tokens,
    SUM(summary_token_count) AS summary_tokens,
    COUNT(*) AS segment_count
FROM conversation_segments
WHERE conversation_id = $1
`

type GetConversationTokenCountRow struct {
	TotalTokens   int64 `json:"total_tokens"`
	SummaryTokens int64 `json:"summary_tokens"`
	SegmentCount  int64 `json:"segment_count"`
}

// Get total tokens in a conversation
func (q *Queries) GetConversationTokenCount(ctx context.Context, conversationID uuid.UUID) (GetConversationTokenCountRow, error) {
	row := q.db.QueryRow(ctx, getConversationTokenCount, conversationID)
	var i GetConversationTokenCountRow
	err := row.Scan(&i.TotalTokens, &i.SummaryTokens, &i.SegmentCount)
	return i, err
}

const getDocumentChunks = `-- name: GetDocumentChunks :many
SELECT id, document_id, chunk_index, content, token_count, embedding, metadata, created_at, doc_id, short_summary, medium_summary, importance FROM document_chunks 
WHERE document_id = $1
ORDER BY chunk_index
`

func (q *Queries) GetDocumentChunks(ctx context.Context, documentID uuid.UUID) ([]DocumentChunk, error) {
	rows, err := q.db.Query(ctx, getDocumentChunks, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentChunk{}
	for rows.Next() {
		var i DocumentChunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.TokenCount,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.DocID,
			&i.ShortSummary,
			&i.MediumSummary,
			&i.Importance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedbackForModel = `-- name: GetFeedbackForModel :many
SELECT f.id, f.routing_event_id, f.user_id, f.rating, f.feedback_type, f.was_regenerated, f.was_edited, f.created_at 
FROM feedback f
JOIN routing_events re ON re.id = f.routing_event_id
WHERE re.selected_model_id = $1
  AND f.created_at >= $2
ORDER BY f.created_at DESC
LIMIT $3
`

type GetFeedbackForModelParams struct {
	SelectedModelID pgtype.UUID        `json:"selected_model_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Limit           int32              `json:"limit"`
}

func (q *Queries) GetFeedbackForModel(ctx context.Context, arg GetFeedbackForModelParams) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, getFeedbackForModel, arg.SelectedModelID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.RoutingEventID,
			&i.UserID,
			&i.Rating,
			&i.FeedbackType,
			&i.WasRegenerated,
			&i.WasEdited,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelRoleScore = `-- name: GetModelRoleScore :one
SELECT id, model_id, role_id, suitability_score, source, updated_at FROM model_role_scores 
WHERE model_id = $1 AND role_id = $2
`

type GetModelRoleScoreParams struct {
	ModelID uuid.UUID `json:"model_id"`
	RoleID  uuid.UUID `json:"role_id"`
}

func (q *Queries) GetModelRoleScore(ctx context.Context, arg GetModelRoleScoreParams) (ModelRoleScore, error) {
	row := q.db.QueryRow(ctx, getModelRoleScore, arg.ModelID, arg.RoleID)
	var i ModelRoleScore
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.RoleID,
		&i.SuitabilityScore,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one

SELECT id, name, description, parent_role_id, default_model_id, max_tokens, max_cost_per_request, created_at FROM roles WHERE id = $1
`

// Roles and policies
func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentRoleID,
		&i.DefaultModelID,
		&i.MaxTokens,
		&i.MaxCostPerRequest,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, parent_role_id, default_model_id, max_tokens, max_cost_per_request, created_at FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentRoleID,
		&i.DefaultModelID,
		&i.MaxTokens,
		&i.MaxCostPerRequest,
		&i.CreatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, parent_role_id, default_model_id, max_tokens, max_cost_per_request, created_at FROM roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentRoleID,
			&i.DefaultModelID,
			&i.MaxTokens,
			&i.MaxCostPerRequest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSegmentSummary = `-- name: UpdateSegmentSummary :exec
UPDATE conversation_segments SET
    summary = $3,
    summary_token_count = $4
WHERE conversation_id = $1 AND segment_index = $2
`

type UpdateSegmentSummaryParams struct {
	ConversationID    uuid.UUID `json:"conversation_id"`
	SegmentIndex      int32     `json:"segment_index"`
	Summary           *string   `json:"summary"`
	SummaryTokenCount *int32    `json:"summary_token_count"`
}

func (q *Queries) UpdateSegmentSummary(ctx context.Context, arg UpdateSegmentSummaryParams) error {
	_, err := q.db.Exec(ctx, updateSegmentSummary,
		arg.ConversationID,
		arg.SegmentIndex,
		arg.Summary,
		arg.SummaryTokenCount,
	)
	return err
}

const upsertModelRoleScore = `-- name: UpsertModelRoleScore :one
INSERT INTO model_role_scores (model_id, role_id, suitability_score, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (model_id, role_id) DO UPDATE SET
    suitability_score = EXCLUDED.suitability_score,
    source = EXCLUDED.source,
    updated_at = NOW()
RETURNING id, model_id, role_id, suitability_score, source, updated_at
`

type UpsertModelRoleScoreParams struct {
	ModelID          uuid.UUID      `json:"model_id"`
	RoleID           uuid.UUID      `json:"role_id"`
	SuitabilityScore pgtype.Numeric `json:"suitability_score"`
	Source           *string        `json:"source"`
}

func (q *Queries) UpsertModelRoleScore(ctx context.Context, arg UpsertModelRoleScoreParams) (ModelRoleScore, error) {
	row := q.db.QueryRow(ctx, upsertModelRoleScore,
		arg.ModelID,
		arg.RoleID,
		arg.SuitabilityScore,
		arg.Source,
	)
	var i ModelRoleScore
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.RoleID,
		&i.SuitabilityScore,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}
