// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const createConversationSegmentWithSession = `-- name: CreateConversationSegmentWithSession :one
INSERT INTO conversation_segments (
    conversation_id, session_id, segment_index, role, content,
    token_count, embedding, short_summary, importance, raw_storage_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, conversation_id, segment_index, role, content, token_count, summary, summary_token_count, embedding, created_at, raw_storage_key, short_summary, importance, session_id
`

type CreateConversationSegmentWithSessionParams struct {
	ConversationID uuid.UUID        `json:"conversation_id"`
	SessionID      pgtype.UUID      `json:"session_id"`
	SegmentIndex   int32            `json:"segment_index"`
	Role           string           `json:"role"`
	Content        string           `json:"content"`
	TokenCount     *int32           `json:"token_count"`
	Embedding      *pgvector.Vector `json:"embedding"`
	ShortSummary   *string          `json:"short_summary"`
	Importance     pgtype.Numeric   `json:"importance"`
	RawStorageKey  *string          `json:"raw_storage_key"`
}

// Creates a segment linked to a session (via session_id from migration 003)
func (q *Queries) CreateConversationSegmentWithSession(ctx context.Context, arg CreateConversationSegmentWithSessionParams) (ConversationSegment, error) {
	row := q.db.QueryRow(ctx, createConversationSegmentWithSession,
		arg.ConversationID,
		arg.SessionID,
		arg.SegmentIndex,
		arg.Role,
		arg.Content,
		arg.TokenCount,
		arg.Embedding,
		arg.ShortSummary,
		arg.Importance,
		arg.RawStorageKey,
	)
	var i ConversationSegment
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SegmentIndex,
		&i.Role,
		&i.Content,
		&i.TokenCount,
		&i.Summary,
		&i.SummaryTokenCount,
		&i.Embedding,
		&i.CreatedAt,
		&i.RawStorageKey,
		&i.ShortSummary,
		&i.Importance,
		&i.SessionID,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (title, source, source_url, source_path, tags, metadata, content_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, source, source_url, source_path, tags, metadata, content_type, total_chunks, total_tokens, source_updated_at, indexed_at, created_at, updated_at
`

type CreateDocumentParams struct {
	Title       string   `json:"title"`
	Source      string   `json:"source"`
	SourceUrl   *string  `json:"source_url"`
	SourcePath  *string  `json:"source_path"`
	Tags        []string `json:"tags"`
	Metadata    []byte   `json:"metadata"`
	ContentType *string  `json:"content_type"`
}

// Documents & Sessions queries
// These extend the base schema with document management and multi-resolution summaries
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.Title,
		arg.Source,
		arg.SourceUrl,
		arg.SourcePath,
		arg.Tags,
		arg.Metadata,
		arg.ContentType,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceUrl,
		&i.SourcePath,
		&i.Tags,
		&i.Metadata,
		&i.ContentType,
		&i.TotalChunks,
		&i.TotalTokens,
		&i.SourceUpdatedAt,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentChunkWithDoc = `-- name: CreateDocumentChunkWithDoc :one
INSERT INTO document_chunks (
    document_id, doc_id, chunk_index, content, token_count,
    embedding, metadata, short_summary, medium_summary
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, document_id, chunk_index, content, token_count, embedding, metadata, created_at, doc_id, short_summary, medium_summary, importance
`

type CreateDocumentChunkWithDocParams struct {
	DocumentID    uuid.UUID        `json:"document_id"`
	DocID         pgtype.UUID      `json:"doc_id"`
	ChunkIndex    int32            `json:"chunk_index"`
	Content       string           `json:"content"`
	TokenCount    *int32           `json:"token_count"`
	Embedding     *pgvector.Vector `json:"embedding"`
	Metadata      []byte           `json:"metadata"`
	ShortSummary  *string          `json:"short_summary"`
	MediumSummary *string          `json:"medium_summary"`
}

// Creates a chunk linked to a document (via doc_id from migration 003)
func (q *Queries) CreateDocumentChunkWithDoc(ctx context.Context, arg CreateDocumentChunkWithDocParams) (DocumentChunk, error) {
	row := q.db.QueryRow(ctx, createDocumentChunkWithDoc,
		arg.DocumentID,
		arg.DocID,
		arg.ChunkIndex,
		arg.Content,
		arg.TokenCount,
		arg.Embedding,
		arg.Metadata,
		arg.ShortSummary,
		arg.MediumSummary,
	)
	var i DocumentChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ChunkIndex,
		&i.Content,
		&i.TokenCount,
		&i.Embedding,
		&i.Metadata,
		&i.CreatedAt,
		&i.DocID,
		&i.ShortSummary,
		&i.MediumSummary,
		&i.Importance,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, org_id, title, role_hint)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, org_id, title, role_hint, total_segments, total_tokens, started_at, last_active_at, ended_at, created_at
`

type CreateSessionParams struct {
	UserID   *string `json:"user_id"`
	OrgID    *string `json:"org_id"`
	Title    *string `json:"title"`
	RoleHint *string `json:"role_hint"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.OrgID,
		arg.Title,
		arg.RoleHint,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Title,
		&i.RoleHint,
		&i.TotalSegments,
		&i.TotalTokens,
		&i.StartedAt,
		&i.LastActiveAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const endSession = `-- name: EndSession :exec
UPDATE sessions SET ended_at = NOW() WHERE id = $1
`

func (q *Queries) EndSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, endSession, id)
	return err
}

const getActiveSessions = `-- name: GetActiveSessions :many
SELECT id, user_id, org_id, title, role_hint, total_segments, total_tokens, started_at, last_active_at, ended_at, created_at FROM sessions WHERE ended_at IS NULL ORDER BY last_active_at DESC
`

func (q *Queries) GetActiveSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, getActiveSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Title,
			&i.RoleHint,
			&i.TotalSegments,
			&i.TotalTokens,
			&i.StartedAt,
			&i.LastActiveAt,
			&i.EndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, source, source_url, source_path, tags, metadata, content_type, total_chunks, total_tokens, source_updated_at, indexed_at, created_at, updated_at FROM documents WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceUrl,
		&i.SourcePath,
		&i.Tags,
		&i.Metadata,
		&i.ContentType,
		&i.TotalChunks,
		&i.TotalTokens,
		&i.SourceUpdatedAt,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentChunksByDocId = `-- name: GetDocumentChunksByDocId :many
SELECT id, document_id, chunk_index, content, token_count, embedding, metadata, created_at, doc_id, short_summary, medium_summary, importance FROM document_chunks
WHERE doc_id = $1
ORDER BY chunk_index
`

func (q *Queries) GetDocumentChunksByDocId(ctx context.Context, docID pgtype.UUID) ([]DocumentChunk, error) {
	rows, err := q.db.Query(ctx, getDocumentChunksByDocId, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentChunk{}
	for rows.Next() {
		var i DocumentChunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.TokenCount,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.DocID,
			&i.ShortSummary,
			&i.MediumSummary,
			&i.Importance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImportantChunks = `-- name: GetImportantChunks :many
SELECT id, document_id, chunk_index, content, token_count, embedding, metadata, created_at, doc_id, short_summary, medium_summary, importance FROM document_chunks
WHERE doc_id = $1 AND importance >= $2
ORDER BY importance DESC
`

type GetImportantChunksParams struct {
	DocID      pgtype.UUID    `json:"doc_id"`
	Importance pgtype.Numeric `json:"importance"`
}

func (q *Queries) GetImportantChunks(ctx context.Context, arg GetImportantChunksParams) ([]DocumentChunk, error) {
	rows, err := q.db.Query(ctx, getImportantChunks, arg.DocID, arg.Importance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentChunk{}
	for rows.Next() {
		var i DocumentChunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.TokenCount,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.DocID,
			&i.ShortSummary,
			&i.MediumSummary,
			&i.Importance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImportantSessionSegments = `-- name: GetImportantSessionSegments :many
SELECT id, conversation_id, segment_index, role, content, token_count, summary, summary_token_count, embedding, created_at, raw_storage_key, short_summary, importance, session_id FROM conversation_segments
WHERE session_id = $1 AND importance >= $2
ORDER BY importance DESC
`

type GetImportantSessionSegmentsParams struct {
	SessionID  pgtype.UUID    `json:"session_id"`
	Importance pgtype.Numeric `json:"importance"`
}

func (q *Queries) GetImportantSessionSegments(ctx context.Context, arg GetImportantSessionSegmentsParams) ([]ConversationSegment, error) {
	rows, err := q.db.Query(ctx, getImportantSessionSegments, arg.SessionID, arg.Importance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationSegment{}
	for rows.Next() {
		var i ConversationSegment
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SegmentIndex,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.Summary,
			&i.SummaryTokenCount,
			&i.Embedding,
			&i.CreatedAt,
			&i.RawStorageKey,
			&i.ShortSummary,
			&i.Importance,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSessionSegments = `-- name: GetRecentSessionSegments :many
SELECT id, conversation_id, segment_index, role, content, token_count, summary, summary_token_count, embedding, created_at, raw_storage_key, short_summary, importance, session_id FROM conversation_segments
WHERE session_id = $1
ORDER BY segment_index DESC
LIMIT $2
`

type GetRecentSessionSegmentsParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) GetRecentSessionSegments(ctx context.Context, arg GetRecentSessionSegmentsParams) ([]ConversationSegment, error) {
	rows, err := q.db.Query(ctx, getRecentSessionSegments, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationSegment{}
	for rows.Next() {
		var i ConversationSegment
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SegmentIndex,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.Summary,
			&i.SummaryTokenCount,
			&i.Embedding,
			&i.CreatedAt,
			&i.RawStorageKey,
			&i.ShortSummary,
			&i.Importance,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, org_id, title, role_hint, total_segments, total_tokens, started_at, last_active_at, ended_at, created_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Title,
		&i.RoleHint,
		&i.TotalSegments,
		&i.TotalTokens,
		&i.StartedAt,
		&i.LastActiveAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionSegments = `-- name: GetSessionSegments :many
SELECT id, conversation_id, segment_index, role, content, token_count, summary, summary_token_count, embedding, created_at, raw_storage_key, short_summary, importance, session_id FROM conversation_segments
WHERE session_id = $1
ORDER BY segment_index
`

func (q *Queries) GetSessionSegments(ctx context.Context, sessionID pgtype.UUID) ([]ConversationSegment, error) {
	rows, err := q.db.Query(ctx, getSessionSegments, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationSegment{}
	for rows.Next() {
		var i ConversationSegment
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SegmentIndex,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.Summary,
			&i.SummaryTokenCount,
			&i.Embedding,
			&i.CreatedAt,
			&i.RawStorageKey,
			&i.ShortSummary,
			&i.Importance,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, user_id, org_id, title, role_hint, total_segments, total_tokens, started_at, last_active_at, ended_at, created_at FROM sessions WHERE user_id = $1 ORDER BY last_active_at DESC LIMIT $2
`

type GetUserSessionsParams struct {
	UserID *string `json:"user_id"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) GetUserSessions(ctx context.Context, arg GetUserSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, getUserSessions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Title,
			&i.RoleHint,
			&i.TotalSegments,
			&i.TotalTokens,
			&i.StartedAt,
			&i.LastActiveAt,
			&i.EndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsBySource = `-- name: ListDocumentsBySource :many
SELECT id, title, source, source_url, source_path, tags, metadata, content_type, total_chunks, total_tokens, source_updated_at, indexed_at, created_at, updated_at FROM documents WHERE source = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListDocumentsBySource(ctx context.Context, source string) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsBySource, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Source,
			&i.SourceUrl,
			&i.SourcePath,
			&i.Tags,
			&i.Metadata,
			&i.ContentType,
			&i.TotalChunks,
			&i.TotalTokens,
			&i.SourceUpdatedAt,
			&i.IndexedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByTags = `-- name: ListDocumentsByTags :many
SELECT id, title, source, source_url, source_path, tags, metadata, content_type, total_chunks, total_tokens, source_updated_at, indexed_at, created_at, updated_at FROM documents WHERE tags && $1 ORDER BY updated_at DESC
`

func (q *Queries) ListDocumentsByTags(ctx context.Context, tags []string) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByTags, tags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Source,
			&i.SourceUrl,
			&i.SourcePath,
			&i.Tags,
			&i.Metadata,
			&i.ContentType,
			&i.TotalChunks,
			&i.TotalTokens,
			&i.SourceUpdatedAt,
			&i.IndexedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChunksInDocument = `-- name: SearchChunksInDocument :many
SELECT id, document_id, chunk_index, content, token_count, embedding, metadata, created_at, doc_id, short_summary, medium_summary, importance, (embedding <-> $1::vector) as distance
FROM document_chunks
WHERE doc_id = $2
ORDER BY embedding <-> $1::vector
LIMIT $3
`

type SearchChunksInDocumentParams struct {
	Column1 pgvector_go.Vector `json:"column_1"`
	DocID   pgtype.UUID        `json:"doc_id"`
	Limit   int32              `json:"limit"`
}

type SearchChunksInDocumentRow struct {
	ID            uuid.UUID          `json:"id"`
	DocumentID    uuid.UUID          `json:"document_id"`
	ChunkIndex    int32              `json:"chunk_index"`
	Content       string             `json:"content"`
	TokenCount    *int32             `json:"token_count"`
	Embedding     *pgvector.Vector   `json:"embedding"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DocID         pgtype.UUID        `json:"doc_id"`
	ShortSummary  *string            `json:"short_summary"`
	MediumSummary *string            `json:"medium_summary"`
	Importance    pgtype.Numeric     `json:"importance"`
	Distance      interface{}        `json:"distance"`
}

func (q *Queries) SearchChunksInDocument(ctx context.Context, arg SearchChunksInDocumentParams) ([]SearchChunksInDocumentRow, error) {
	rows, err := q.db.Query(ctx, searchChunksInDocument, arg.Column1, arg.DocID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchChunksInDocumentRow{}
	for rows.Next() {
		var i SearchChunksInDocumentRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.TokenCount,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.DocID,
			&i.ShortSummary,
			&i.MediumSummary,
			&i.Importance,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentChunksBySimilarity = `-- name: SearchDocumentChunksBySimilarity :many
SELECT dc.id, dc.document_id, dc.chunk_index, dc.content, dc.token_count, dc.embedding, dc.metadata, dc.created_at, dc.doc_id, dc.short_summary, dc.medium_summary, dc.importance, d.title, d.source,
    (dc.embedding <-> $1::vector) as distance
FROM document_chunks dc
JOIN documents d ON dc.doc_id = d.id
ORDER BY dc.embedding <-> $1::vector
LIMIT $2
`

type SearchDocumentChunksBySimilarityParams struct {
	Column1 pgvector_go.Vector `json:"column_1"`
	Limit   int32              `json:"limit"`
}

type SearchDocumentChunksBySimilarityRow struct {
	ID            uuid.UUID          `json:"id"`
	DocumentID    uuid.UUID          `json:"document_id"`
	ChunkIndex    int32              `json:"chunk_index"`
	Content       string             `json:"content"`
	TokenCount    *int32             `json:"token_count"`
	Embedding     *pgvector.Vector   `json:"embedding"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DocID         pgtype.UUID        `json:"doc_id"`
	ShortSummary  *string            `json:"short_summary"`
	MediumSummary *string            `json:"medium_summary"`
	Importance    pgtype.Numeric     `json:"importance"`
	Title         string             `json:"title"`
	Source        string             `json:"source"`
	Distance      interface{}        `json:"distance"`
}

func (q *Queries) SearchDocumentChunksBySimilarity(ctx context.Context, arg SearchDocumentChunksBySimilarityParams) ([]SearchDocumentChunksBySimilarityRow, error) {
	rows, err := q.db.Query(ctx, searchDocumentChunksBySimilarity, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentChunksBySimilarityRow{}
	for rows.Next() {
		var i SearchDocumentChunksBySimilarityRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.TokenCount,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.DocID,
			&i.ShortSummary,
			&i.MediumSummary,
			&i.Importance,
			&i.Title,
			&i.Source,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSessionSegments = `-- name: SearchSessionSegments :many
SELECT id, conversation_id, segment_index, role, content, token_count, summary, summary_token_count, embedding, created_at, raw_storage_key, short_summary, importance, session_id, (embedding <-> $1::vector) as distance
FROM conversation_segments
WHERE session_id = $2
ORDER BY embedding <-> $1::vector
LIMIT $3
`

type SearchSessionSegmentsParams struct {
	Column1   pgvector_go.Vector `json:"column_1"`
	SessionID pgtype.UUID        `json:"session_id"`
	Limit     int32              `json:"limit"`
}

type SearchSessionSegmentsRow struct {
	ID                uuid.UUID          `json:"id"`
	ConversationID    uuid.UUID          `json:"conversation_id"`
	SegmentIndex      int32              `json:"segment_index"`
	Role              string             `json:"role"`
	Content           string             `json:"content"`
	TokenCount        *int32             `json:"token_count"`
	Summary           *string            `json:"summary"`
	SummaryTokenCount *int32             `json:"summary_token_count"`
	Embedding         *pgvector.Vector   `json:"embedding"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RawStorageKey     *string            `json:"raw_storage_key"`
	ShortSummary      *string            `json:"short_summary"`
	Importance        pgtype.Numeric     `json:"importance"`
	SessionID         pgtype.UUID        `json:"session_id"`
	Distance          interface{}        `json:"distance"`
}

func (q *Queries) SearchSessionSegments(ctx context.Context, arg SearchSessionSegmentsParams) ([]SearchSessionSegmentsRow, error) {
	rows, err := q.db.Query(ctx, searchSessionSegments, arg.Column1, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSessionSegmentsRow{}
	for rows.Next() {
		var i SearchSessionSegmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SegmentIndex,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.Summary,
			&i.SummaryTokenCount,
			&i.Embedding,
			&i.CreatedAt,
			&i.RawStorageKey,
			&i.ShortSummary,
			&i.Importance,
			&i.SessionID,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChunkMultiSummaries = `-- name: UpdateChunkMultiSummaries :exec
UPDATE document_chunks SET
    short_summary = $2,
    medium_summary = $3
WHERE id = $1
`

type UpdateChunkMultiSummariesParams struct {
	ID            uuid.UUID `json:"id"`
	ShortSummary  *string   `json:"short_summary"`
	MediumSummary *string   `json:"medium_summary"`
}

func (q *Queries) UpdateChunkMultiSummaries(ctx context.Context, arg UpdateChunkMultiSummariesParams) error {
	_, err := q.db.Exec(ctx, updateChunkMultiSummaries, arg.ID, arg.ShortSummary, arg.MediumSummary)
	return err
}

const updateDocumentStats = `-- name: UpdateDocumentStats :exec
UPDATE documents SET
    total_chunks = $2,
    total_tokens = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDocumentStatsParams struct {
	ID          uuid.UUID `json:"id"`
	TotalChunks *int32    `json:"total_chunks"`
	TotalTokens *int32    `json:"total_tokens"`
}

func (q *Queries) UpdateDocumentStats(ctx context.Context, arg UpdateDocumentStatsParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStats, arg.ID, arg.TotalChunks, arg.TotalTokens)
	return err
}

const updateSegmentImportance = `-- name: UpdateSegmentImportance :exec
UPDATE conversation_segments SET importance = $2 WHERE id = $1
`

type UpdateSegmentImportanceParams struct {
	ID         uuid.UUID      `json:"id"`
	Importance pgtype.Numeric `json:"importance"`
}

func (q *Queries) UpdateSegmentImportance(ctx context.Context, arg UpdateSegmentImportanceParams) error {
	_, err := q.db.Exec(ctx, updateSegmentImportance, arg.ID, arg.Importance)
	return err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions SET
    last_active_at = NOW(),
    total_segments = total_segments + 1,
    total_tokens = total_tokens + $2
WHERE id = $1
`

type UpdateSessionActivityParams struct {
	ID          uuid.UUID `json:"id"`
	TotalTokens *int32    `json:"total_tokens"`
}

func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error {
	_, err := q.db.Exec(ctx, updateSessionActivity, arg.ID, arg.TotalTokens)
	return err
}
