// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AccountUsageSnapshot struct {
	ID               uuid.UUID          `json:"id"`
	AccountID        uuid.UUID          `json:"account_id"`
	EndpointID       pgtype.UUID        `json:"endpoint_id"`
	WindowType       string             `json:"window_type"`
	WindowStart      pgtype.Timestamptz `json:"window_start"`
	WindowEnd        pgtype.Timestamptz `json:"window_end"`
	TokensIn         *int64             `json:"tokens_in"`
	TokensOut        *int64             `json:"tokens_out"`
	Requests         *int32             `json:"requests"`
	CreditsUsed      pgtype.Numeric     `json:"credits_used"`
	CostUsd          pgtype.Numeric     `json:"cost_usd"`
	PercentRemaining pgtype.Numeric     `json:"percent_remaining"`
	LastRefreshedAt  pgtype.Timestamptz `json:"last_refreshed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type BanditState struct {
	ID          uuid.UUID          `json:"id"`
	ModelID     uuid.UUID          `json:"model_id"`
	RoleID      pgtype.UUID        `json:"role_id"`
	Alpha       pgtype.Numeric     `json:"alpha"`
	Beta        pgtype.Numeric     `json:"beta"`
	TotalTrials *int32             `json:"total_trials"`
	LastUpdated pgtype.Timestamptz `json:"last_updated"`
}

type ConversationSegment struct {
	ID                uuid.UUID          `json:"id"`
	ConversationID    uuid.UUID          `json:"conversation_id"`
	SegmentIndex      int32              `json:"segment_index"`
	Role              string             `json:"role"`
	Content           string             `json:"content"`
	TokenCount        *int32             `json:"token_count"`
	Summary           *string            `json:"summary"`
	SummaryTokenCount *int32             `json:"summary_token_count"`
	Embedding         *pgvector.Vector   `json:"embedding"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RawStorageKey     *string            `json:"raw_storage_key"`
	ShortSummary      *string            `json:"short_summary"`
	Importance        pgtype.Numeric     `json:"importance"`
	SessionID         pgtype.UUID        `json:"session_id"`
}

type Document struct {
	ID              uuid.UUID          `json:"id"`
	Title           string             `json:"title"`
	Source          string             `json:"source"`
	SourceUrl       *string            `json:"source_url"`
	SourcePath      *string            `json:"source_path"`
	Tags            []string           `json:"tags"`
	Metadata        []byte             `json:"metadata"`
	ContentType     *string            `json:"content_type"`
	TotalChunks     *int32             `json:"total_chunks"`
	TotalTokens     *int32             `json:"total_tokens"`
	SourceUpdatedAt pgtype.Timestamptz `json:"source_updated_at"`
	IndexedAt       pgtype.Timestamptz `json:"indexed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DocumentChunk struct {
	ID            uuid.UUID          `json:"id"`
	DocumentID    uuid.UUID          `json:"document_id"`
	ChunkIndex    int32              `json:"chunk_index"`
	Content       string             `json:"content"`
	TokenCount    *int32             `json:"token_count"`
	Embedding     *pgvector.Vector   `json:"embedding"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DocID         pgtype.UUID        `json:"doc_id"`
	ShortSummary  *string            `json:"short_summary"`
	MediumSummary *string            `json:"medium_summary"`
	Importance    pgtype.Numeric     `json:"importance"`
}

type EndpointHealth struct {
	ID                   uuid.UUID          `json:"id"`
	EndpointID           uuid.UUID          `json:"endpoint_id"`
	ConsecutiveFailures  *int32             `json:"consecutive_failures"`
	ConsecutiveSuccesses *int32             `json:"consecutive_successes"`
	LastSuccessAt        pgtype.Timestamptz `json:"last_success_at"`
	LastFailureAt        pgtype.Timestamptz `json:"last_failure_at"`
	LastError            *string            `json:"last_error"`
	AvgLatencyMs         *int32             `json:"avg_latency_ms"`
	P95LatencyMs         *int32             `json:"p95_latency_ms"`
	SuccessRate          pgtype.Numeric     `json:"success_rate"`
	IsHealthy            *bool              `json:"is_healthy"`
	HealthCheckAt        pgtype.Timestamptz `json:"health_check_at"`
}

type Feedback struct {
	ID             uuid.UUID          `json:"id"`
	RoutingEventID pgtype.UUID        `json:"routing_event_id"`
	UserID         *string            `json:"user_id"`
	Rating         *int32             `json:"rating"`
	FeedbackType   *string            `json:"feedback_type"`
	WasRegenerated *bool              `json:"was_regenerated"`
	WasEdited      *bool              `json:"was_edited"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Model struct {
	ID                uuid.UUID          `json:"id"`
	Provider          string             `json:"provider"`
	ModelName         string             `json:"model_name"`
	DisplayName       *string            `json:"display_name"`
	Status            string             `json:"status"`
	ContextWindow     int32              `json:"context_window"`
	MaxOutputTokens   *int32             `json:"max_output_tokens"`
	SupportsTools     *bool              `json:"supports_tools"`
	SupportsVision    *bool              `json:"supports_vision"`
	SupportsStreaming *bool              `json:"supports_streaming"`
	InputCostPer1k    pgtype.Numeric     `json:"input_cost_per_1k"`
	OutputCostPer1k   pgtype.Numeric     `json:"output_cost_per_1k"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ModelAbility struct {
	ID                   uuid.UUID          `json:"id"`
	ModelID              uuid.UUID          `json:"model_id"`
	Reasoning            pgtype.Numeric     `json:"reasoning"`
	Coding               pgtype.Numeric     `json:"coding"`
	Math                 pgtype.Numeric     `json:"math"`
	Writing              pgtype.Numeric     `json:"writing"`
	Analysis             pgtype.Numeric     `json:"analysis"`
	Creativity           pgtype.Numeric     `json:"creativity"`
	InstructionFollowing pgtype.Numeric     `json:"instruction_following"`
	Multilingual         pgtype.Numeric     `json:"multilingual"`
	CalibratedAt         pgtype.Timestamptz `json:"calibrated_at"`
	SampleCount          *int32             `json:"sample_count"`
}

type ModelEndpoint struct {
	ID                uuid.UUID          `json:"id"`
	AccountID         uuid.UUID          `json:"account_id"`
	ModelID           uuid.UUID          `json:"model_id"`
	Transport         string             `json:"transport"`
	UpstreamRoute     *string            `json:"upstream_route"`
	BaseUrl           *string            `json:"base_url"`
	PricingBasis      *string            `json:"pricing_basis"`
	UnitPriceInput    pgtype.Numeric     `json:"unit_price_input"`
	UnitPriceOutput   pgtype.Numeric     `json:"unit_price_output"`
	LatencyEstimateMs *int32             `json:"latency_estimate_ms"`
	ThroughputTps     pgtype.Numeric     `json:"throughput_tps"`
	Priority          *int32             `json:"priority"`
	QualityTier       *string            `json:"quality_tier"`
	Status            *string            `json:"status"`
	CooldownUntil     pgtype.Timestamptz `json:"cooldown_until"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ModelMetric struct {
	ID                uuid.UUID          `json:"id"`
	ModelID           uuid.UUID          `json:"model_id"`
	MetricSource      string             `json:"metric_source"`
	IntelligenceIndex pgtype.Numeric     `json:"intelligence_index"`
	GpqaDiamond       pgtype.Numeric     `json:"gpqa_diamond"`
	Aime2024          pgtype.Numeric     `json:"aime_2024"`
	Hle               pgtype.Numeric     `json:"hle"`
	Musr              pgtype.Numeric     `json:"musr"`
	Humaneval         pgtype.Numeric     `json:"humaneval"`
	Livecodebench     pgtype.Numeric     `json:"livecodebench"`
	ChatbotArenaElo   *int32             `json:"chatbot_arena_elo"`
	AvgLatencyMs      *int32             `json:"avg_latency_ms"`
	ThroughputTps     pgtype.Numeric     `json:"throughput_tps"`
	CollectedAt       pgtype.Timestamptz `json:"collected_at"`
}

type ModelRoleScore struct {
	ID               uuid.UUID          `json:"id"`
	ModelID          uuid.UUID          `json:"model_id"`
	RoleID           uuid.UUID          `json:"role_id"`
	SuitabilityScore pgtype.Numeric     `json:"suitability_score"`
	Source           *string            `json:"source"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ModelSemanticProfile struct {
	ID                   uuid.UUID          `json:"id"`
	ModelID              uuid.UUID          `json:"model_id"`
	Description          *string            `json:"description"`
	DescriptionEmbedding *pgvector.Vector   `json:"description_embedding"`
	Strengths            []string           `json:"strengths"`
	Weaknesses           []string           `json:"weaknesses"`
	BestFor              []string           `json:"best_for"`
	AvoidFor             []string           `json:"avoid_for"`
	PersonalityTraits    []byte             `json:"personality_traits"`
	CommunitySentiment   pgtype.Numeric     `json:"community_sentiment"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type ProviderAccount struct {
	ID                     uuid.UUID          `json:"id"`
	Name                   string             `json:"name"`
	BackendType            string             `json:"backend_type"`
	BillingModel           string             `json:"billing_model"`
	BaseCurrency           *string            `json:"base_currency"`
	SubscriptionFeeMonthly pgtype.Numeric     `json:"subscription_fee_monthly"`
	IsActive               *bool              `json:"is_active"`
	Notes                  *string            `json:"notes"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type ProviderAccountLimit struct {
	ID              uuid.UUID          `json:"id"`
	AccountID       uuid.UUID          `json:"account_id"`
	LimitType       string             `json:"limit_type"`
	WindowSeconds   int32              `json:"window_seconds"`
	LimitValue      pgtype.Numeric     `json:"limit_value"`
	IsHard          *bool              `json:"is_hard"`
	CooldownSeconds *int32             `json:"cooldown_seconds"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Description       *string            `json:"description"`
	ParentRoleID      pgtype.UUID        `json:"parent_role_id"`
	DefaultModelID    pgtype.UUID        `json:"default_model_id"`
	MaxTokens         *int32             `json:"max_tokens"`
	MaxCostPerRequest pgtype.Numeric     `json:"max_cost_per_request"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type RoutingEvent struct {
	ID                 uuid.UUID          `json:"id"`
	RequestID          uuid.UUID          `json:"request_id"`
	UserID             *string            `json:"user_id"`
	OrgID              *string            `json:"org_id"`
	RoleID             pgtype.UUID        `json:"role_id"`
	TaskType           *string            `json:"task_type"`
	DifficultyEstimate pgtype.Numeric     `json:"difficulty_estimate"`
	SelectedModelID    pgtype.UUID        `json:"selected_model_id"`
	FallbackModels     []uuid.UUID        `json:"fallback_models"`
	RoutingMethod      *string            `json:"routing_method"`
	RoutingLatencyMs   *int32             `json:"routing_latency_ms"`
	ModelLatencyMs     *int32             `json:"model_latency_ms"`
	TokensUsed         *int32             `json:"tokens_used"`
	Cost               pgtype.Numeric     `json:"cost"`
	Success            *bool              `json:"success"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID            uuid.UUID          `json:"id"`
	UserID        *string            `json:"user_id"`
	OrgID         *string            `json:"org_id"`
	Title         *string            `json:"title"`
	RoleHint      *string            `json:"role_hint"`
	TotalSegments *int32             `json:"total_segments"`
	TotalTokens   *int32             `json:"total_tokens"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	LastActiveAt  pgtype.Timestamptz `json:"last_active_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Tool struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	Provider             string             `json:"provider"`
	Description          *string            `json:"description"`
	SchemaJson           []byte             `json:"schema_json"`
	AvgLatencyMs         *int32             `json:"avg_latency_ms"`
	AvgCost              pgtype.Numeric     `json:"avg_cost"`
	RiskLevel            *string            `json:"risk_level"`
	RequiresConfirmation *bool              `json:"requires_confirmation"`
	RateLimitPerMin      *int32             `json:"rate_limit_per_min"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type ToolMetric struct {
	ID               uuid.UUID          `json:"id"`
	ToolID           uuid.UUID          `json:"tool_id"`
	SuccessRate      pgtype.Numeric     `json:"success_rate"`
	AvgExecutionMs   *int32             `json:"avg_execution_ms"`
	P95ExecutionMs   *int32             `json:"p95_execution_ms"`
	ErrorRate        pgtype.Numeric     `json:"error_rate"`
	LastSuccessAt    pgtype.Timestamptz `json:"last_success_at"`
	LastFailureAt    pgtype.Timestamptz `json:"last_failure_at"`
	TotalInvocations *int32             `json:"total_invocations"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ToolRoleScore struct {
	ID               uuid.UUID          `json:"id"`
	ToolID           uuid.UUID          `json:"tool_id"`
	RoleID           uuid.UUID          `json:"role_id"`
	SuitabilityScore pgtype.Numeric     `json:"suitability_score"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ToolSemanticProfile struct {
	ID                   uuid.UUID          `json:"id"`
	ToolID               uuid.UUID          `json:"tool_id"`
	DescriptionEmbedding *pgvector.Vector   `json:"description_embedding"`
	SuitableFor          []string           `json:"suitable_for"`
	RequiresContext      []string           `json:"requires_context"`
	OutputType           *string            `json:"output_type"`
	SideEffects          *bool              `json:"side_effects"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
