// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: models.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createModel = `-- name: CreateModel :one
INSERT INTO models (
    provider, model_name, display_name, status, 
    context_window, max_output_tokens,
    supports_tools, supports_vision, supports_streaming,
    input_cost_per_1k, output_cost_per_1k
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, provider, model_name, display_name, status, context_window, max_output_tokens, supports_tools, supports_vision, supports_streaming, input_cost_per_1k, output_cost_per_1k, created_at, updated_at
`

type CreateModelParams struct {
	Provider          string         `json:"provider"`
	ModelName         string         `json:"model_name"`
	DisplayName       *string        `json:"display_name"`
	Status            string         `json:"status"`
	ContextWindow     int32          `json:"context_window"`
	MaxOutputTokens   *int32         `json:"max_output_tokens"`
	SupportsTools     *bool          `json:"supports_tools"`
	SupportsVision    *bool          `json:"supports_vision"`
	SupportsStreaming *bool          `json:"supports_streaming"`
	InputCostPer1k    pgtype.Numeric `json:"input_cost_per_1k"`
	OutputCostPer1k   pgtype.Numeric `json:"output_cost_per_1k"`
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, createModel,
		arg.Provider,
		arg.ModelName,
		arg.DisplayName,
		arg.Status,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.SupportsTools,
		arg.SupportsVision,
		arg.SupportsStreaming,
		arg.InputCostPer1k,
		arg.OutputCostPer1k,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ModelName,
		&i.DisplayName,
		&i.Status,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.SupportsTools,
		&i.SupportsVision,
		&i.SupportsStreaming,
		&i.InputCostPer1k,
		&i.OutputCostPer1k,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSimilarModels = `-- name: FindSimilarModels :many
SELECT m.id, m.provider, m.model_name, m.display_name, m.status, m.context_window, m.max_output_tokens, m.supports_tools, m.supports_vision, m.supports_streaming, m.input_cost_per_1k, m.output_cost_per_1k, m.created_at, m.updated_at, msp.description_embedding <-> $1 AS distance
FROM models m
JOIN model_semantic_profiles msp ON msp.model_id = m.id
WHERE m.status = 'active'
ORDER BY distance
LIMIT $2
`

type FindSimilarModelsParams struct {
	DescriptionEmbedding *pgvector.Vector `json:"description_embedding"`
	Limit                int32            `json:"limit"`
}

type FindSimilarModelsRow struct {
	ID                uuid.UUID          `json:"id"`
	Provider          string             `json:"provider"`
	ModelName         string             `json:"model_name"`
	DisplayName       *string            `json:"display_name"`
	Status            string             `json:"status"`
	ContextWindow     int32              `json:"context_window"`
	MaxOutputTokens   *int32             `json:"max_output_tokens"`
	SupportsTools     *bool              `json:"supports_tools"`
	SupportsVision    *bool              `json:"supports_vision"`
	SupportsStreaming *bool              `json:"supports_streaming"`
	InputCostPer1k    pgtype.Numeric     `json:"input_cost_per_1k"`
	OutputCostPer1k   pgtype.Numeric     `json:"output_cost_per_1k"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Distance          interface{}        `json:"distance"`
}

func (q *Queries) FindSimilarModels(ctx context.Context, arg FindSimilarModelsParams) ([]FindSimilarModelsRow, error) {
	rows, err := q.db.Query(ctx, findSimilarModels, arg.DescriptionEmbedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSimilarModelsRow{}
	for rows.Next() {
		var i FindSimilarModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelName,
			&i.DisplayName,
			&i.Status,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.SupportsTools,
			&i.SupportsVision,
			&i.SupportsStreaming,
			&i.InputCostPer1k,
			&i.OutputCostPer1k,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModel = `-- name: GetModel :one

SELECT id, provider, model_name, display_name, status, context_window, max_output_tokens, supports_tools, supports_vision, supports_streaming, input_cost_per_1k, output_cost_per_1k, created_at, updated_at FROM models WHERE id = $1
`

// Models CRUD and queries
func (q *Queries) GetModel(ctx context.Context, id uuid.UUID) (Model, error) {
	row := q.db.QueryRow(ctx, getModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ModelName,
		&i.DisplayName,
		&i.Status,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.SupportsTools,
		&i.SupportsVision,
		&i.SupportsStreaming,
		&i.InputCostPer1k,
		&i.OutputCostPer1k,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelAbilities = `-- name: GetModelAbilities :one
SELECT id, model_id, reasoning, coding, math, writing, analysis, creativity, instruction_following, multilingual, calibrated_at, sample_count FROM model_abilities WHERE model_id = $1
`

func (q *Queries) GetModelAbilities(ctx context.Context, modelID uuid.UUID) (ModelAbility, error) {
	row := q.db.QueryRow(ctx, getModelAbilities, modelID)
	var i ModelAbility
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Reasoning,
		&i.Coding,
		&i.Math,
		&i.Writing,
		&i.Analysis,
		&i.Creativity,
		&i.InstructionFollowing,
		&i.Multilingual,
		&i.CalibratedAt,
		&i.SampleCount,
	)
	return i, err
}

const getModelByName = `-- name: GetModelByName :one
SELECT id, provider, model_name, display_name, status, context_window, max_output_tokens, supports_tools, supports_vision, supports_streaming, input_cost_per_1k, output_cost_per_1k, created_at, updated_at FROM models WHERE provider = $1 AND model_name = $2
`

type GetModelByNameParams struct {
	Provider  string `json:"provider"`
	ModelName string `json:"model_name"`
}

func (q *Queries) GetModelByName(ctx context.Context, arg GetModelByNameParams) (Model, error) {
	row := q.db.QueryRow(ctx, getModelByName, arg.Provider, arg.ModelName)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ModelName,
		&i.DisplayName,
		&i.Status,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.SupportsTools,
		&i.SupportsVision,
		&i.SupportsStreaming,
		&i.InputCostPer1k,
		&i.OutputCostPer1k,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelMetrics = `-- name: GetModelMetrics :one
SELECT id, model_id, metric_source, intelligence_index, gpqa_diamond, aime_2024, hle, musr, humaneval, livecodebench, chatbot_arena_elo, avg_latency_ms, throughput_tps, collected_at FROM model_metrics WHERE model_id = $1 AND metric_source = $2
`

type GetModelMetricsParams struct {
	ModelID      uuid.UUID `json:"model_id"`
	MetricSource string    `json:"metric_source"`
}

func (q *Queries) GetModelMetrics(ctx context.Context, arg GetModelMetricsParams) (ModelMetric, error) {
	row := q.db.QueryRow(ctx, getModelMetrics, arg.ModelID, arg.MetricSource)
	var i ModelMetric
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.MetricSource,
		&i.IntelligenceIndex,
		&i.GpqaDiamond,
		&i.Aime2024,
		&i.Hle,
		&i.Musr,
		&i.Humaneval,
		&i.Livecodebench,
		&i.ChatbotArenaElo,
		&i.AvgLatencyMs,
		&i.ThroughputTps,
		&i.CollectedAt,
	)
	return i, err
}

const getModelSemanticProfile = `-- name: GetModelSemanticProfile :one
SELECT id, model_id, description, description_embedding, strengths, weaknesses, best_for, avoid_for, personality_traits, community_sentiment, updated_at FROM model_semantic_profiles WHERE model_id = $1
`

func (q *Queries) GetModelSemanticProfile(ctx context.Context, modelID uuid.UUID) (ModelSemanticProfile, error) {
	row := q.db.QueryRow(ctx, getModelSemanticProfile, modelID)
	var i ModelSemanticProfile
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Description,
		&i.DescriptionEmbedding,
		&i.Strengths,
		&i.Weaknesses,
		&i.BestFor,
		&i.AvoidFor,
		&i.PersonalityTraits,
		&i.CommunitySentiment,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveModels = `-- name: ListActiveModels :many
SELECT id, provider, model_name, display_name, status, context_window, max_output_tokens, supports_tools, supports_vision, supports_streaming, input_cost_per_1k, output_cost_per_1k, created_at, updated_at FROM models WHERE status = 'active' ORDER BY provider, model_name
`

func (q *Queries) ListActiveModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listActiveModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelName,
			&i.DisplayName,
			&i.Status,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.SupportsTools,
			&i.SupportsVision,
			&i.SupportsStreaming,
			&i.InputCostPer1k,
			&i.OutputCostPer1k,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT id, provider, model_name, display_name, status, context_window, max_output_tokens, supports_tools, supports_vision, supports_streaming, input_cost_per_1k, output_cost_per_1k, created_at, updated_at FROM models 
WHERE status = COALESCE($1, status)
ORDER BY provider, model_name
`

func (q *Queries) ListModels(ctx context.Context, status *string) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelName,
			&i.DisplayName,
			&i.Status,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.SupportsTools,
			&i.SupportsVision,
			&i.SupportsStreaming,
			&i.InputCostPer1k,
			&i.OutputCostPer1k,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModel = `-- name: UpdateModel :one
UPDATE models SET
    display_name = COALESCE($2, display_name),
    status = COALESCE($3, status),
    context_window = COALESCE($4, context_window),
    max_output_tokens = COALESCE($5, max_output_tokens),
    input_cost_per_1k = COALESCE($6, input_cost_per_1k),
    output_cost_per_1k = COALESCE($7, output_cost_per_1k),
    updated_at = NOW()
WHERE id = $1
RETURNING id, provider, model_name, display_name, status, context_window, max_output_tokens, supports_tools, supports_vision, supports_streaming, input_cost_per_1k, output_cost_per_1k, created_at, updated_at
`

type UpdateModelParams struct {
	ID              uuid.UUID      `json:"id"`
	DisplayName     *string        `json:"display_name"`
	Status          *string        `json:"status"`
	ContextWindow   *int32         `json:"context_window"`
	MaxOutputTokens *int32         `json:"max_output_tokens"`
	InputCostPer1k  pgtype.Numeric `json:"input_cost_per_1k"`
	OutputCostPer1k pgtype.Numeric `json:"output_cost_per_1k"`
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, updateModel,
		arg.ID,
		arg.DisplayName,
		arg.Status,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.InputCostPer1k,
		arg.OutputCostPer1k,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ModelName,
		&i.DisplayName,
		&i.Status,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.SupportsTools,
		&i.SupportsVision,
		&i.SupportsStreaming,
		&i.InputCostPer1k,
		&i.OutputCostPer1k,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertModelAbilities = `-- name: UpsertModelAbilities :one
INSERT INTO model_abilities (
    model_id, reasoning, coding, math, writing,
    analysis, creativity, instruction_following, multilingual,
    calibrated_at, sample_count
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), $10
) ON CONFLICT (model_id) DO UPDATE SET
    reasoning = EXCLUDED.reasoning,
    coding = EXCLUDED.coding,
    math = EXCLUDED.math,
    writing = EXCLUDED.writing,
    analysis = EXCLUDED.analysis,
    creativity = EXCLUDED.creativity,
    instruction_following = EXCLUDED.instruction_following,
    multilingual = EXCLUDED.multilingual,
    calibrated_at = NOW(),
    sample_count = EXCLUDED.sample_count
RETURNING id, model_id, reasoning, coding, math, writing, analysis, creativity, instruction_following, multilingual, calibrated_at, sample_count
`

type UpsertModelAbilitiesParams struct {
	ModelID              uuid.UUID      `json:"model_id"`
	Reasoning            pgtype.Numeric `json:"reasoning"`
	Coding               pgtype.Numeric `json:"coding"`
	Math                 pgtype.Numeric `json:"math"`
	Writing              pgtype.Numeric `json:"writing"`
	Analysis             pgtype.Numeric `json:"analysis"`
	Creativity           pgtype.Numeric `json:"creativity"`
	InstructionFollowing pgtype.Numeric `json:"instruction_following"`
	Multilingual         pgtype.Numeric `json:"multilingual"`
	SampleCount          *int32         `json:"sample_count"`
}

func (q *Queries) UpsertModelAbilities(ctx context.Context, arg UpsertModelAbilitiesParams) (ModelAbility, error) {
	row := q.db.QueryRow(ctx, upsertModelAbilities,
		arg.ModelID,
		arg.Reasoning,
		arg.Coding,
		arg.Math,
		arg.Writing,
		arg.Analysis,
		arg.Creativity,
		arg.InstructionFollowing,
		arg.Multilingual,
		arg.SampleCount,
	)
	var i ModelAbility
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Reasoning,
		&i.Coding,
		&i.Math,
		&i.Writing,
		&i.Analysis,
		&i.Creativity,
		&i.InstructionFollowing,
		&i.Multilingual,
		&i.CalibratedAt,
		&i.SampleCount,
	)
	return i, err
}

const upsertModelMetrics = `-- name: UpsertModelMetrics :one
INSERT INTO model_metrics (
    model_id, metric_source, intelligence_index,
    gpqa_diamond, aime_2024, hle, musr,
    humaneval, livecodebench, chatbot_arena_elo,
    avg_latency_ms, throughput_tps
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) ON CONFLICT (model_id, metric_source) DO UPDATE SET
    intelligence_index = EXCLUDED.intelligence_index,
    gpqa_diamond = EXCLUDED.gpqa_diamond,
    aime_2024 = EXCLUDED.aime_2024,
    hle = EXCLUDED.hle,
    musr = EXCLUDED.musr,
    humaneval = EXCLUDED.humaneval,
    livecodebench = EXCLUDED.livecodebench,
    chatbot_arena_elo = EXCLUDED.chatbot_arena_elo,
    avg_latency_ms = EXCLUDED.avg_latency_ms,
    throughput_tps = EXCLUDED.throughput_tps,
    collected_at = NOW()
RETURNING id, model_id, metric_source, intelligence_index, gpqa_diamond, aime_2024, hle, musr, humaneval, livecodebench, chatbot_arena_elo, avg_latency_ms, throughput_tps, collected_at
`

type UpsertModelMetricsParams struct {
	ModelID           uuid.UUID      `json:"model_id"`
	MetricSource      string         `json:"metric_source"`
	IntelligenceIndex pgtype.Numeric `json:"intelligence_index"`
	GpqaDiamond       pgtype.Numeric `json:"gpqa_diamond"`
	Aime2024          pgtype.Numeric `json:"aime_2024"`
	Hle               pgtype.Numeric `json:"hle"`
	Musr              pgtype.Numeric `json:"musr"`
	Humaneval         pgtype.Numeric `json:"humaneval"`
	Livecodebench     pgtype.Numeric `json:"livecodebench"`
	ChatbotArenaElo   *int32         `json:"chatbot_arena_elo"`
	AvgLatencyMs      *int32         `json:"avg_latency_ms"`
	ThroughputTps     pgtype.Numeric `json:"throughput_tps"`
}

func (q *Queries) UpsertModelMetrics(ctx context.Context, arg UpsertModelMetricsParams) (ModelMetric, error) {
	row := q.db.QueryRow(ctx, upsertModelMetrics,
		arg.ModelID,
		arg.MetricSource,
		arg.IntelligenceIndex,
		arg.GpqaDiamond,
		arg.Aime2024,
		arg.Hle,
		arg.Musr,
		arg.Humaneval,
		arg.Livecodebench,
		arg.ChatbotArenaElo,
		arg.AvgLatencyMs,
		arg.ThroughputTps,
	)
	var i ModelMetric
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.MetricSource,
		&i.IntelligenceIndex,
		&i.GpqaDiamond,
		&i.Aime2024,
		&i.Hle,
		&i.Musr,
		&i.Humaneval,
		&i.Livecodebench,
		&i.ChatbotArenaElo,
		&i.AvgLatencyMs,
		&i.ThroughputTps,
		&i.CollectedAt,
	)
	return i, err
}

const upsertModelSemanticProfile = `-- name: UpsertModelSemanticProfile :one
INSERT INTO model_semantic_profiles (
    model_id, description, description_embedding,
    strengths, weaknesses, best_for, avoid_for,
    personality_traits, community_sentiment
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) ON CONFLICT (model_id) DO UPDATE SET
    description = EXCLUDED.description,
    description_embedding = EXCLUDED.description_embedding,
    strengths = EXCLUDED.strengths,
    weaknesses = EXCLUDED.weaknesses,
    best_for = EXCLUDED.best_for,
    avoid_for = EXCLUDED.avoid_for,
    personality_traits = EXCLUDED.personality_traits,
    community_sentiment = EXCLUDED.community_sentiment,
    updated_at = NOW()
RETURNING id, model_id, description, description_embedding, strengths, weaknesses, best_for, avoid_for, personality_traits, community_sentiment, updated_at
`

type UpsertModelSemanticProfileParams struct {
	ModelID              uuid.UUID        `json:"model_id"`
	Description          *string          `json:"description"`
	DescriptionEmbedding *pgvector.Vector `json:"description_embedding"`
	Strengths            []string         `json:"strengths"`
	Weaknesses           []string         `json:"weaknesses"`
	BestFor              []string         `json:"best_for"`
	AvoidFor             []string         `json:"avoid_for"`
	PersonalityTraits    []byte           `json:"personality_traits"`
	CommunitySentiment   pgtype.Numeric   `json:"community_sentiment"`
}

func (q *Queries) UpsertModelSemanticProfile(ctx context.Context, arg UpsertModelSemanticProfileParams) (ModelSemanticProfile, error) {
	row := q.db.QueryRow(ctx, upsertModelSemanticProfile,
		arg.ModelID,
		arg.Description,
		arg.DescriptionEmbedding,
		arg.Strengths,
		arg.Weaknesses,
		arg.BestFor,
		arg.AvoidFor,
		arg.PersonalityTraits,
		arg.CommunitySentiment,
	)
	var i ModelSemanticProfile
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.Description,
		&i.DescriptionEmbedding,
		&i.Strengths,
		&i.Weaknesses,
		&i.BestFor,
		&i.AvoidFor,
		&i.PersonalityTraits,
		&i.CommunitySentiment,
		&i.UpdatedAt,
	)
	return i, err
}
