// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createRoutingEvent = `-- name: CreateRoutingEvent :one
INSERT INTO routing_events (
    request_id, user_id, org_id, role_id,
    task_type, difficulty_estimate,
    selected_model_id, fallback_models,
    routing_method, routing_latency_ms
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, request_id, user_id, org_id, role_id, task_type, difficulty_estimate, selected_model_id, fallback_models, routing_method, routing_latency_ms, model_latency_ms, tokens_used, cost, success, created_at
`

type CreateRoutingEventParams struct {
	RequestID          uuid.UUID      `json:"request_id"`
	UserID             *string        `json:"user_id"`
	OrgID              *string        `json:"org_id"`
	RoleID             pgtype.UUID    `json:"role_id"`
	TaskType           *string        `json:"task_type"`
	DifficultyEstimate pgtype.Numeric `json:"difficulty_estimate"`
	SelectedModelID    pgtype.UUID    `json:"selected_model_id"`
	FallbackModels     []uuid.UUID    `json:"fallback_models"`
	RoutingMethod      *string        `json:"routing_method"`
	RoutingLatencyMs   *int32         `json:"routing_latency_ms"`
}

func (q *Queries) CreateRoutingEvent(ctx context.Context, arg CreateRoutingEventParams) (RoutingEvent, error) {
	row := q.db.QueryRow(ctx, createRoutingEvent,
		arg.RequestID,
		arg.UserID,
		arg.OrgID,
		arg.RoleID,
		arg.TaskType,
		arg.DifficultyEstimate,
		arg.SelectedModelID,
		arg.FallbackModels,
		arg.RoutingMethod,
		arg.RoutingLatencyMs,
	)
	var i RoutingEvent
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.UserID,
		&i.OrgID,
		&i.RoleID,
		&i.TaskType,
		&i.DifficultyEstimate,
		&i.SelectedModelID,
		&i.FallbackModels,
		&i.RoutingMethod,
		&i.RoutingLatencyMs,
		&i.ModelLatencyMs,
		&i.TokensUsed,
		&i.Cost,
		&i.Success,
		&i.CreatedAt,
	)
	return i, err
}

const getCheapestModels = `-- name: GetCheapestModels :many
SELECT m.id, m.provider, m.model_name, m.display_name, m.status, m.context_window, m.max_output_tokens, m.supports_tools, m.supports_vision, m.supports_streaming, m.input_cost_per_1k, m.output_cost_per_1k, m.created_at, m.updated_at, 
    ma.reasoning + ma.coding + ma.math AS total_ability,
    m.input_cost_per_1k + m.output_cost_per_1k AS total_cost
FROM models m
LEFT JOIN model_abilities ma ON ma.model_id = m.id
WHERE m.status = 'active'
  AND (ma.reasoning + ma.coding + ma.math) >= COALESCE($1, 0)
ORDER BY total_cost ASC
LIMIT $2
`

type GetCheapestModelsParams struct {
	Reasoning pgtype.Numeric `json:"reasoning"`
	Limit     int32          `json:"limit"`
}

type GetCheapestModelsRow struct {
	ID                uuid.UUID          `json:"id"`
	Provider          string             `json:"provider"`
	ModelName         string             `json:"model_name"`
	DisplayName       *string            `json:"display_name"`
	Status            string             `json:"status"`
	ContextWindow     int32              `json:"context_window"`
	MaxOutputTokens   *int32             `json:"max_output_tokens"`
	SupportsTools     *bool              `json:"supports_tools"`
	SupportsVision    *bool              `json:"supports_vision"`
	SupportsStreaming *bool              `json:"supports_streaming"`
	InputCostPer1k    pgtype.Numeric     `json:"input_cost_per_1k"`
	OutputCostPer1k   pgtype.Numeric     `json:"output_cost_per_1k"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TotalAbility      int32              `json:"total_ability"`
	TotalCost         int32              `json:"total_cost"`
}

// Get cheapest models that meet minimum ability threshold
func (q *Queries) GetCheapestModels(ctx context.Context, arg GetCheapestModelsParams) ([]GetCheapestModelsRow, error) {
	rows, err := q.db.Query(ctx, getCheapestModels, arg.Reasoning, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCheapestModelsRow{}
	for rows.Next() {
		var i GetCheapestModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelName,
			&i.DisplayName,
			&i.Status,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.SupportsTools,
			&i.SupportsVision,
			&i.SupportsStreaming,
			&i.InputCostPer1k,
			&i.OutputCostPer1k,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalAbility,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFastestModels = `-- name: GetFastestModels :many
SELECT m.id, m.provider, m.model_name, m.display_name, m.status, m.context_window, m.max_output_tokens, m.supports_tools, m.supports_vision, m.supports_streaming, m.input_cost_per_1k, m.output_cost_per_1k, m.created_at, m.updated_at, 
    mm.avg_latency_ms,
    ma.reasoning + ma.coding AS ability_score
FROM models m
LEFT JOIN model_metrics mm ON mm.model_id = m.id AND mm.metric_source = 'artificialanalysis'
LEFT JOIN model_abilities ma ON ma.model_id = m.id
WHERE m.status = 'active'
  AND (ma.reasoning + ma.coding) >= COALESCE($1, 0)
ORDER BY mm.avg_latency_ms ASC NULLS LAST
LIMIT $2
`

type GetFastestModelsParams struct {
	Reasoning pgtype.Numeric `json:"reasoning"`
	Limit     int32          `json:"limit"`
}

type GetFastestModelsRow struct {
	ID                uuid.UUID          `json:"id"`
	Provider          string             `json:"provider"`
	ModelName         string             `json:"model_name"`
	DisplayName       *string            `json:"display_name"`
	Status            string             `json:"status"`
	ContextWindow     int32              `json:"context_window"`
	MaxOutputTokens   *int32             `json:"max_output_tokens"`
	SupportsTools     *bool              `json:"supports_tools"`
	SupportsVision    *bool              `json:"supports_vision"`
	SupportsStreaming *bool              `json:"supports_streaming"`
	InputCostPer1k    pgtype.Numeric     `json:"input_cost_per_1k"`
	OutputCostPer1k   pgtype.Numeric     `json:"output_cost_per_1k"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AvgLatencyMs      *int32             `json:"avg_latency_ms"`
	AbilityScore      int32              `json:"ability_score"`
}

// Get fastest models that meet minimum ability threshold
func (q *Queries) GetFastestModels(ctx context.Context, arg GetFastestModelsParams) ([]GetFastestModelsRow, error) {
	rows, err := q.db.Query(ctx, getFastestModels, arg.Reasoning, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFastestModelsRow{}
	for rows.Next() {
		var i GetFastestModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelName,
			&i.DisplayName,
			&i.Status,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.SupportsTools,
			&i.SupportsVision,
			&i.SupportsStreaming,
			&i.InputCostPer1k,
			&i.OutputCostPer1k,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvgLatencyMs,
			&i.AbilityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelsBySemanticMatch = `-- name: GetModelsBySemanticMatch :many
SELECT 
    m.id,
    m.provider,
    m.model_name,
    msp.description,
    msp.strengths,
    msp.best_for,
    msp.description_embedding <-> $1 AS semantic_distance
FROM models m
JOIN model_semantic_profiles msp ON msp.model_id = m.id
WHERE m.status = 'active'
ORDER BY semantic_distance
LIMIT $2
`

type GetModelsBySemanticMatchParams struct {
	DescriptionEmbedding *pgvector.Vector `json:"description_embedding"`
	Limit                int32            `json:"limit"`
}

type GetModelsBySemanticMatchRow struct {
	ID               uuid.UUID   `json:"id"`
	Provider         string      `json:"provider"`
	ModelName        string      `json:"model_name"`
	Description      *string     `json:"description"`
	Strengths        []string    `json:"strengths"`
	BestFor          []string    `json:"best_for"`
	SemanticDistance interface{} `json:"semantic_distance"`
}

// Find models whose semantic profile matches the query embedding
func (q *Queries) GetModelsBySemanticMatch(ctx context.Context, arg GetModelsBySemanticMatchParams) ([]GetModelsBySemanticMatchRow, error) {
	rows, err := q.db.Query(ctx, getModelsBySemanticMatch, arg.DescriptionEmbedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetModelsBySemanticMatchRow{}
	for rows.Next() {
		var i GetModelsBySemanticMatchRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelName,
			&i.Description,
			&i.Strengths,
			&i.BestFor,
			&i.SemanticDistance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelsForRole = `-- name: GetModelsForRole :many
SELECT 
    m.id, m.provider, m.model_name, m.display_name, m.status, m.context_window, m.max_output_tokens, m.supports_tools, m.supports_vision, m.supports_streaming, m.input_cost_per_1k, m.output_cost_per_1k, m.created_at, m.updated_at,
    mrs.suitability_score,
    ma.reasoning + ma.coding AS composite_ability,
    mm.chatbot_arena_elo
FROM models m
JOIN model_role_scores mrs ON mrs.model_id = m.id
LEFT JOIN model_abilities ma ON ma.model_id = m.id
LEFT JOIN model_metrics mm ON mm.model_id = m.id AND mm.metric_source = 'lmsys'
WHERE mrs.role_id = $1
  AND m.status = 'active'
ORDER BY mrs.suitability_score DESC
LIMIT $2
`

type GetModelsForRoleParams struct {
	RoleID uuid.UUID `json:"role_id"`
	Limit  int32     `json:"limit"`
}

type GetModelsForRoleRow struct {
	ID                uuid.UUID          `json:"id"`
	Provider          string             `json:"provider"`
	ModelName         string             `json:"model_name"`
	DisplayName       *string            `json:"display_name"`
	Status            string             `json:"status"`
	ContextWindow     int32              `json:"context_window"`
	MaxOutputTokens   *int32             `json:"max_output_tokens"`
	SupportsTools     *bool              `json:"supports_tools"`
	SupportsVision    *bool              `json:"supports_vision"`
	SupportsStreaming *bool              `json:"supports_streaming"`
	InputCostPer1k    pgtype.Numeric     `json:"input_cost_per_1k"`
	OutputCostPer1k   pgtype.Numeric     `json:"output_cost_per_1k"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SuitabilityScore  pgtype.Numeric     `json:"suitability_score"`
	CompositeAbility  int32              `json:"composite_ability"`
	ChatbotArenaElo   *int32             `json:"chatbot_arena_elo"`
}

// Get models ranked by role suitability
func (q *Queries) GetModelsForRole(ctx context.Context, arg GetModelsForRoleParams) ([]GetModelsForRoleRow, error) {
	rows, err := q.db.Query(ctx, getModelsForRole, arg.RoleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetModelsForRoleRow{}
	for rows.Next() {
		var i GetModelsForRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelName,
			&i.DisplayName,
			&i.Status,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.SupportsTools,
			&i.SupportsVision,
			&i.SupportsStreaming,
			&i.InputCostPer1k,
			&i.OutputCostPer1k,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuitabilityScore,
			&i.CompositeAbility,
			&i.ChatbotArenaElo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelsForRouting = `-- name: GetModelsForRouting :many

SELECT 
    m.id,
    m.provider,
    m.model_name,
    m.status,
    m.context_window,
    m.input_cost_per_1k,
    m.output_cost_per_1k,
    ma.reasoning,
    ma.coding,
    ma.math,
    ma.writing,
    ma.analysis,
    mm.intelligence_index,
    mm.chatbot_arena_elo,
    mm.avg_latency_ms,
    bs.alpha,
    bs.beta,
    bs.alpha / (bs.alpha + bs.beta) AS bandit_mean
FROM models m
LEFT JOIN model_abilities ma ON ma.model_id = m.id
LEFT JOIN model_metrics mm ON mm.model_id = m.id AND mm.metric_source = 'artificialanalysis'
LEFT JOIN bandit_state bs ON bs.model_id = m.id AND (bs.role_id = $1 OR bs.role_id IS NULL)
WHERE m.status = 'active'
ORDER BY mm.intelligence_index DESC NULLS LAST
`

type GetModelsForRoutingRow struct {
	ID                uuid.UUID      `json:"id"`
	Provider          string         `json:"provider"`
	ModelName         string         `json:"model_name"`
	Status            string         `json:"status"`
	ContextWindow     int32          `json:"context_window"`
	InputCostPer1k    pgtype.Numeric `json:"input_cost_per_1k"`
	OutputCostPer1k   pgtype.Numeric `json:"output_cost_per_1k"`
	Reasoning         pgtype.Numeric `json:"reasoning"`
	Coding            pgtype.Numeric `json:"coding"`
	Math              pgtype.Numeric `json:"math"`
	Writing           pgtype.Numeric `json:"writing"`
	Analysis          pgtype.Numeric `json:"analysis"`
	IntelligenceIndex pgtype.Numeric `json:"intelligence_index"`
	ChatbotArenaElo   *int32         `json:"chatbot_arena_elo"`
	AvgLatencyMs      *int32         `json:"avg_latency_ms"`
	Alpha             pgtype.Numeric `json:"alpha"`
	Beta              pgtype.Numeric `json:"beta"`
	BanditMean        int32          `json:"bandit_mean"`
}

// Routing queries - the core of intelligent model selection
// Main routing query: get models with abilities, metrics, and bandit scores
func (q *Queries) GetModelsForRouting(ctx context.Context, roleID pgtype.UUID) ([]GetModelsForRoutingRow, error) {
	rows, err := q.db.Query(ctx, getModelsForRouting, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetModelsForRoutingRow{}
	for rows.Next() {
		var i GetModelsForRoutingRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelName,
			&i.Status,
			&i.ContextWindow,
			&i.InputCostPer1k,
			&i.OutputCostPer1k,
			&i.Reasoning,
			&i.Coding,
			&i.Math,
			&i.Writing,
			&i.Analysis,
			&i.IntelligenceIndex,
			&i.ChatbotArenaElo,
			&i.AvgLatencyMs,
			&i.Alpha,
			&i.Beta,
			&i.BanditMean,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelsForTask = `-- name: GetModelsForTask :many
SELECT 
    m.id, m.provider, m.model_name, m.display_name, m.status, m.context_window, m.max_output_tokens, m.supports_tools, m.supports_vision, m.supports_streaming, m.input_cost_per_1k, m.output_cost_per_1k, m.created_at, m.updated_at,
    CASE 
        WHEN $1 = 'coding' THEN ma.coding
        WHEN $1 = 'math' THEN ma.math
        WHEN $1 = 'writing' THEN ma.writing
        WHEN $1 = 'reasoning' THEN ma.reasoning
        WHEN $1 = 'analysis' THEN ma.analysis
        ELSE ma.reasoning -- default
    END AS task_ability,
    mm.avg_latency_ms,
    m.input_cost_per_1k + m.output_cost_per_1k AS total_cost
FROM models m
LEFT JOIN model_abilities ma ON ma.model_id = m.id
LEFT JOIN model_metrics mm ON mm.model_id = m.id AND mm.metric_source = 'artificialanalysis'
WHERE m.status = 'active'
ORDER BY task_ability DESC NULLS LAST
LIMIT $2
`

type GetModelsForTaskParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
}

type GetModelsForTaskRow struct {
	ID                uuid.UUID          `json:"id"`
	Provider          string             `json:"provider"`
	ModelName         string             `json:"model_name"`
	DisplayName       *string            `json:"display_name"`
	Status            string             `json:"status"`
	ContextWindow     int32              `json:"context_window"`
	MaxOutputTokens   *int32             `json:"max_output_tokens"`
	SupportsTools     *bool              `json:"supports_tools"`
	SupportsVision    *bool              `json:"supports_vision"`
	SupportsStreaming *bool              `json:"supports_streaming"`
	InputCostPer1k    pgtype.Numeric     `json:"input_cost_per_1k"`
	OutputCostPer1k   pgtype.Numeric     `json:"output_cost_per_1k"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TaskAbility       interface{}        `json:"task_ability"`
	AvgLatencyMs      *int32             `json:"avg_latency_ms"`
	TotalCost         int32              `json:"total_cost"`
}

// Get models ranked by ability for a specific task type
func (q *Queries) GetModelsForTask(ctx context.Context, arg GetModelsForTaskParams) ([]GetModelsForTaskRow, error) {
	rows, err := q.db.Query(ctx, getModelsForTask, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetModelsForTaskRow{}
	for rows.Next() {
		var i GetModelsForTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelName,
			&i.DisplayName,
			&i.Status,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.SupportsTools,
			&i.SupportsVision,
			&i.SupportsStreaming,
			&i.InputCostPer1k,
			&i.OutputCostPer1k,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskAbility,
			&i.AvgLatencyMs,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoutingStats = `-- name: GetRoutingStats :one
SELECT
    selected_model_id,
    COUNT(*) AS total_requests,
    COUNT(*) FILTER (WHERE success = true) AS successful_requests,
    AVG(model_latency_ms) AS avg_latency,
    SUM(cost) AS total_cost,
    SUM(tokens_used) AS total_tokens
FROM routing_events
WHERE selected_model_id = $1
  AND created_at >= $2
GROUP BY selected_model_id
`

type GetRoutingStatsParams struct {
	SelectedModelID pgtype.UUID        `json:"selected_model_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type GetRoutingStatsRow struct {
	SelectedModelID    pgtype.UUID `json:"selected_model_id"`
	TotalRequests      int64       `json:"total_requests"`
	SuccessfulRequests int64       `json:"successful_requests"`
	AvgLatency         float64     `json:"avg_latency"`
	TotalCost          int64       `json:"total_cost"`
	TotalTokens        int64       `json:"total_tokens"`
}

// Aggregate routing stats for a model over a time period
func (q *Queries) GetRoutingStats(ctx context.Context, arg GetRoutingStatsParams) (GetRoutingStatsRow, error) {
	row := q.db.QueryRow(ctx, getRoutingStats, arg.SelectedModelID, arg.CreatedAt)
	var i GetRoutingStatsRow
	err := row.Scan(
		&i.SelectedModelID,
		&i.TotalRequests,
		&i.SuccessfulRequests,
		&i.AvgLatency,
		&i.TotalCost,
		&i.TotalTokens,
	)
	return i, err
}

const updateRoutingEventCompletion = `-- name: UpdateRoutingEventCompletion :exec
UPDATE routing_events SET
    model_latency_ms = $2,
    tokens_used = $3,
    cost = $4,
    success = $5
WHERE id = $1
`

type UpdateRoutingEventCompletionParams struct {
	ID             uuid.UUID      `json:"id"`
	ModelLatencyMs *int32         `json:"model_latency_ms"`
	TokensUsed     *int32         `json:"tokens_used"`
	Cost           pgtype.Numeric `json:"cost"`
	Success        *bool          `json:"success"`
}

func (q *Queries) UpdateRoutingEventCompletion(ctx context.Context, arg UpdateRoutingEventCompletionParams) error {
	_, err := q.db.Exec(ctx, updateRoutingEventCompletion,
		arg.ID,
		arg.ModelLatencyMs,
		arg.TokensUsed,
		arg.Cost,
		arg.Success,
	)
	return err
}
