// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tools.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createTool = `-- name: CreateTool :one
INSERT INTO tools (
    name, provider, description, schema_json,
    avg_latency_ms, avg_cost, risk_level,
    requires_confirmation, rate_limit_per_min
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, provider, description, schema_json, avg_latency_ms, avg_cost, risk_level, requires_confirmation, rate_limit_per_min, status, created_at, updated_at
`

type CreateToolParams struct {
	Name                 string         `json:"name"`
	Provider             string         `json:"provider"`
	Description          *string        `json:"description"`
	SchemaJson           []byte         `json:"schema_json"`
	AvgLatencyMs         *int32         `json:"avg_latency_ms"`
	AvgCost              pgtype.Numeric `json:"avg_cost"`
	RiskLevel            *string        `json:"risk_level"`
	RequiresConfirmation *bool          `json:"requires_confirmation"`
	RateLimitPerMin      *int32         `json:"rate_limit_per_min"`
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, createTool,
		arg.Name,
		arg.Provider,
		arg.Description,
		arg.SchemaJson,
		arg.AvgLatencyMs,
		arg.AvgCost,
		arg.RiskLevel,
		arg.RequiresConfirmation,
		arg.RateLimitPerMin,
	)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Description,
		&i.SchemaJson,
		&i.AvgLatencyMs,
		&i.AvgCost,
		&i.RiskLevel,
		&i.RequiresConfirmation,
		&i.RateLimitPerMin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSimilarTools = `-- name: FindSimilarTools :many
SELECT 
    t.id, t.name, t.provider, t.description, t.schema_json, t.avg_latency_ms, t.avg_cost, t.risk_level, t.requires_confirmation, t.rate_limit_per_min, t.status, t.created_at, t.updated_at,
    tsp.description_embedding <-> $1 AS distance,
    tsp.suitable_for,
    tsp.side_effects
FROM tools t
JOIN tool_semantic_profiles tsp ON tsp.tool_id = t.id
WHERE t.status = 'active'
ORDER BY distance
LIMIT $2
`

type FindSimilarToolsParams struct {
	DescriptionEmbedding *pgvector.Vector `json:"description_embedding"`
	Limit                int32            `json:"limit"`
}

type FindSimilarToolsRow struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	Provider             string             `json:"provider"`
	Description          *string            `json:"description"`
	SchemaJson           []byte             `json:"schema_json"`
	AvgLatencyMs         *int32             `json:"avg_latency_ms"`
	AvgCost              pgtype.Numeric     `json:"avg_cost"`
	RiskLevel            *string            `json:"risk_level"`
	RequiresConfirmation *bool              `json:"requires_confirmation"`
	RateLimitPerMin      *int32             `json:"rate_limit_per_min"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Distance             interface{}        `json:"distance"`
	SuitableFor          []string           `json:"suitable_for"`
	SideEffects          *bool              `json:"side_effects"`
}

// Find tools by semantic similarity
func (q *Queries) FindSimilarTools(ctx context.Context, arg FindSimilarToolsParams) ([]FindSimilarToolsRow, error) {
	rows, err := q.db.Query(ctx, findSimilarTools, arg.DescriptionEmbedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSimilarToolsRow{}
	for rows.Next() {
		var i FindSimilarToolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Description,
			&i.SchemaJson,
			&i.AvgLatencyMs,
			&i.AvgCost,
			&i.RiskLevel,
			&i.RequiresConfirmation,
			&i.RateLimitPerMin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Distance,
			&i.SuitableFor,
			&i.SideEffects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSafeTools = `-- name: GetSafeTools :many
SELECT t.id, t.name, t.provider, t.description, t.schema_json, t.avg_latency_ms, t.avg_cost, t.risk_level, t.requires_confirmation, t.rate_limit_per_min, t.status, t.created_at, t.updated_at
FROM tools t
JOIN tool_semantic_profiles tsp ON tsp.tool_id = t.id
WHERE t.status = 'active'
  AND t.risk_level IN ('low', 'medium')
  AND tsp.side_effects = false
  AND t.requires_confirmation = false
ORDER BY t.name
`

// Get tools that don't have side effects (safe for auto-execution)
func (q *Queries) GetSafeTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.Query(ctx, getSafeTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tool{}
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Description,
			&i.SchemaJson,
			&i.AvgLatencyMs,
			&i.AvgCost,
			&i.RiskLevel,
			&i.RequiresConfirmation,
			&i.RateLimitPerMin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTool = `-- name: GetTool :one

SELECT id, name, provider, description, schema_json, avg_latency_ms, avg_cost, risk_level, requires_confirmation, rate_limit_per_min, status, created_at, updated_at FROM tools WHERE id = $1
`

// Tool registry and tool routing queries
func (q *Queries) GetTool(ctx context.Context, id uuid.UUID) (Tool, error) {
	row := q.db.QueryRow(ctx, getTool, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Description,
		&i.SchemaJson,
		&i.AvgLatencyMs,
		&i.AvgCost,
		&i.RiskLevel,
		&i.RequiresConfirmation,
		&i.RateLimitPerMin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolByName = `-- name: GetToolByName :one
SELECT id, name, provider, description, schema_json, avg_latency_ms, avg_cost, risk_level, requires_confirmation, rate_limit_per_min, status, created_at, updated_at FROM tools WHERE name = $1
`

func (q *Queries) GetToolByName(ctx context.Context, name string) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolByName, name)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Description,
		&i.SchemaJson,
		&i.AvgLatencyMs,
		&i.AvgCost,
		&i.RiskLevel,
		&i.RequiresConfirmation,
		&i.RateLimitPerMin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolSemanticProfile = `-- name: GetToolSemanticProfile :one
SELECT id, tool_id, description_embedding, suitable_for, requires_context, output_type, side_effects, updated_at FROM tool_semantic_profiles WHERE tool_id = $1
`

func (q *Queries) GetToolSemanticProfile(ctx context.Context, toolID uuid.UUID) (ToolSemanticProfile, error) {
	row := q.db.QueryRow(ctx, getToolSemanticProfile, toolID)
	var i ToolSemanticProfile
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.DescriptionEmbedding,
		&i.SuitableFor,
		&i.RequiresContext,
		&i.OutputType,
		&i.SideEffects,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolsForRole = `-- name: GetToolsForRole :many
SELECT 
    t.id, t.name, t.provider, t.description, t.schema_json, t.avg_latency_ms, t.avg_cost, t.risk_level, t.requires_confirmation, t.rate_limit_per_min, t.status, t.created_at, t.updated_at,
    trs.suitability_score,
    tm.success_rate,
    tm.avg_execution_ms
FROM tools t
JOIN tool_role_scores trs ON trs.tool_id = t.id
LEFT JOIN tool_metrics tm ON tm.tool_id = t.id
WHERE trs.role_id = $1
  AND t.status = 'active'
ORDER BY trs.suitability_score DESC
LIMIT $2
`

type GetToolsForRoleParams struct {
	RoleID uuid.UUID `json:"role_id"`
	Limit  int32     `json:"limit"`
}

type GetToolsForRoleRow struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	Provider             string             `json:"provider"`
	Description          *string            `json:"description"`
	SchemaJson           []byte             `json:"schema_json"`
	AvgLatencyMs         *int32             `json:"avg_latency_ms"`
	AvgCost              pgtype.Numeric     `json:"avg_cost"`
	RiskLevel            *string            `json:"risk_level"`
	RequiresConfirmation *bool              `json:"requires_confirmation"`
	RateLimitPerMin      *int32             `json:"rate_limit_per_min"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	SuitabilityScore     pgtype.Numeric     `json:"suitability_score"`
	SuccessRate          pgtype.Numeric     `json:"success_rate"`
	AvgExecutionMs       *int32             `json:"avg_execution_ms"`
}

// Get tools suitable for a role
func (q *Queries) GetToolsForRole(ctx context.Context, arg GetToolsForRoleParams) ([]GetToolsForRoleRow, error) {
	rows, err := q.db.Query(ctx, getToolsForRole, arg.RoleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetToolsForRoleRow{}
	for rows.Next() {
		var i GetToolsForRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Description,
			&i.SchemaJson,
			&i.AvgLatencyMs,
			&i.AvgCost,
			&i.RiskLevel,
			&i.RequiresConfirmation,
			&i.RateLimitPerMin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuitabilityScore,
			&i.SuccessRate,
			&i.AvgExecutionMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTools = `-- name: ListTools :many
SELECT id, name, provider, description, schema_json, avg_latency_ms, avg_cost, risk_level, requires_confirmation, rate_limit_per_min, status, created_at, updated_at FROM tools 
WHERE status = 'active'
ORDER BY name
`

func (q *Queries) ListTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tool{}
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Description,
			&i.SchemaJson,
			&i.AvgLatencyMs,
			&i.AvgCost,
			&i.RiskLevel,
			&i.RequiresConfirmation,
			&i.RateLimitPerMin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolsByProvider = `-- name: ListToolsByProvider :many
SELECT id, name, provider, description, schema_json, avg_latency_ms, avg_cost, risk_level, requires_confirmation, rate_limit_per_min, status, created_at, updated_at FROM tools 
WHERE provider = $1 AND status = 'active'
ORDER BY name
`

func (q *Queries) ListToolsByProvider(ctx context.Context, provider string) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listToolsByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tool{}
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Description,
			&i.SchemaJson,
			&i.AvgLatencyMs,
			&i.AvgCost,
			&i.RiskLevel,
			&i.RequiresConfirmation,
			&i.RateLimitPerMin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTool = `-- name: UpdateTool :one
UPDATE tools SET
    description = COALESCE($2, description),
    schema_json = COALESCE($3, schema_json),
    avg_latency_ms = COALESCE($4, avg_latency_ms),
    avg_cost = COALESCE($5, avg_cost),
    risk_level = COALESCE($6, risk_level),
    status = COALESCE($7, status),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, provider, description, schema_json, avg_latency_ms, avg_cost, risk_level, requires_confirmation, rate_limit_per_min, status, created_at, updated_at
`

type UpdateToolParams struct {
	ID           uuid.UUID      `json:"id"`
	Description  *string        `json:"description"`
	SchemaJson   []byte         `json:"schema_json"`
	AvgLatencyMs *int32         `json:"avg_latency_ms"`
	AvgCost      pgtype.Numeric `json:"avg_cost"`
	RiskLevel    *string        `json:"risk_level"`
	Status       *string        `json:"status"`
}

func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, updateTool,
		arg.ID,
		arg.Description,
		arg.SchemaJson,
		arg.AvgLatencyMs,
		arg.AvgCost,
		arg.RiskLevel,
		arg.Status,
	)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Description,
		&i.SchemaJson,
		&i.AvgLatencyMs,
		&i.AvgCost,
		&i.RiskLevel,
		&i.RequiresConfirmation,
		&i.RateLimitPerMin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateToolMetrics = `-- name: UpdateToolMetrics :exec
UPDATE tool_metrics SET
    success_rate = $2,
    avg_execution_ms = $3,
    p95_execution_ms = $4,
    error_rate = $5,
    total_invocations = total_invocations + 1,
    last_success_at = CASE WHEN $6 THEN NOW() ELSE last_success_at END,
    last_failure_at = CASE WHEN NOT $6 THEN NOW() ELSE last_failure_at END,
    updated_at = NOW()
WHERE tool_id = $1
`

type UpdateToolMetricsParams struct {
	ToolID         uuid.UUID          `json:"tool_id"`
	SuccessRate    pgtype.Numeric     `json:"success_rate"`
	AvgExecutionMs *int32             `json:"avg_execution_ms"`
	P95ExecutionMs *int32             `json:"p95_execution_ms"`
	ErrorRate      pgtype.Numeric     `json:"error_rate"`
	LastSuccessAt  pgtype.Timestamptz `json:"last_success_at"`
}

func (q *Queries) UpdateToolMetrics(ctx context.Context, arg UpdateToolMetricsParams) error {
	_, err := q.db.Exec(ctx, updateToolMetrics,
		arg.ToolID,
		arg.SuccessRate,
		arg.AvgExecutionMs,
		arg.P95ExecutionMs,
		arg.ErrorRate,
		arg.LastSuccessAt,
	)
	return err
}

const upsertToolSemanticProfile = `-- name: UpsertToolSemanticProfile :one
INSERT INTO tool_semantic_profiles (
    tool_id, description_embedding, suitable_for,
    requires_context, output_type, side_effects
) VALUES (
    $1, $2, $3, $4, $5, $6
) ON CONFLICT (tool_id) DO UPDATE SET
    description_embedding = EXCLUDED.description_embedding,
    suitable_for = EXCLUDED.suitable_for,
    requires_context = EXCLUDED.requires_context,
    output_type = EXCLUDED.output_type,
    side_effects = EXCLUDED.side_effects,
    updated_at = NOW()
RETURNING id, tool_id, description_embedding, suitable_for, requires_context, output_type, side_effects, updated_at
`

type UpsertToolSemanticProfileParams struct {
	ToolID               uuid.UUID        `json:"tool_id"`
	DescriptionEmbedding *pgvector.Vector `json:"description_embedding"`
	SuitableFor          []string         `json:"suitable_for"`
	RequiresContext      []string         `json:"requires_context"`
	OutputType           *string          `json:"output_type"`
	SideEffects          *bool            `json:"side_effects"`
}

func (q *Queries) UpsertToolSemanticProfile(ctx context.Context, arg UpsertToolSemanticProfileParams) (ToolSemanticProfile, error) {
	row := q.db.QueryRow(ctx, upsertToolSemanticProfile,
		arg.ToolID,
		arg.DescriptionEmbedding,
		arg.SuitableFor,
		arg.RequiresContext,
		arg.OutputType,
		arg.SideEffects,
	)
	var i ToolSemanticProfile
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.DescriptionEmbedding,
		&i.SuitableFor,
		&i.RequiresContext,
		&i.OutputType,
		&i.SideEffects,
		&i.UpdatedAt,
	)
	return i, err
}
