import type { RegistryModel } from "../providers/shared.ts";

export const FACTORY_CHAT_MODELS_BEFORE_MINIMAX: RegistryModel[] = [
  {
    id: "inkling",
    name: "Inkling (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 1040000,
    maxOutputTokens: 32768,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "mistral-medium-3.5",
    name: "Mistral Medium 3.5 (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 256000,
    maxOutputTokens: 64000,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "glm-5.3",
    name: "GLM 5.3 (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 1040000,
    maxOutputTokens: 131072,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "glm-5.3-flash",
    name: "GLM 5.3 Flash (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 1048576,
    maxOutputTokens: 131072,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "glm-5.2",
    name: "GLM 5.2 (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 1040000,
    maxOutputTokens: 131072,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "glm-5.2-fast",
    name: "GLM 5.2 Fast (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 524288,
    maxOutputTokens: 131072,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "glm-5.1",
    name: "GLM 5.1 [Deprecated] (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 200000,
    maxOutputTokens: 65536,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "glm-5",
    name: "GLM 5 [Deprecated] (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 222000,
    maxOutputTokens: 32000,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "glm-4.7",
    name: "GLM 4.7 [Deprecated] (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 223344,
    maxOutputTokens: 25344,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "glm-4.6",
    name: "GLM 4.6 (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 328000,
    maxOutputTokens: 128000,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "kimi-k3",
    name: "Kimi K3 (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 262144,
    maxOutputTokens: 65536,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "kimi-k2.7-code",
    name: "Kimi K2.7 Code (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 262144,
    maxOutputTokens: 65536,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6 (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 262144,
    maxOutputTokens: 65536,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5 [Deprecated] (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 288768,
    maxOutputTokens: 32768,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "deepseek-v4.1-flash",
    name: "DeepSeek V4.1 Flash (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1040000,
    maxOutputTokens: 131072,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "deepseek-v4-flash-0731",
    name: "DeepSeek V4 Flash [Deprecated] (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 1040000,
    maxOutputTokens: 131072,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro [Deprecated] (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 1040000,
    maxOutputTokens: 131072,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
];

export const FACTORY_CHAT_MODELS_AFTER_MINIMAX: RegistryModel[] = [
  {
    id: "nemotron-3-ultra",
    name: "Nemotron 3 Ultra (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 202000,
    maxOutputTokens: 65536,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
  {
    id: "qwen3.8-max",
    name: "Qwen3.8 Max (Factory Core)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 262144,
    maxOutputTokens: 131072,
    targetFormat: "openai",
    interleavedField: "reasoning_content",
  },
];

export const FACTORY_CHAT_MODELS: RegistryModel[] = [
  ...FACTORY_CHAT_MODELS_BEFORE_MINIMAX,
  ...FACTORY_CHAT_MODELS_AFTER_MINIMAX,
];
