import type { RegistryModel } from "../providers/shared.ts";

export const FACTORY_GEMINI_MODELS: RegistryModel[] = [
  {
    id: "gemini-3.8-flash",
    name: "Gemini 3.8 Flash (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["low", "medium", "high"],
    supportsVision: true,
    contextLength: 1065536,
    maxOutputTokens: 65536,
    targetFormat: "gemini",
  },
  {
    id: "gemini-3.7-flash",
    name: "Gemini 3.7 Flash (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["low", "medium", "high"],
    supportsVision: true,
    contextLength: 1065536,
    maxOutputTokens: 65536,
    targetFormat: "gemini",
  },
  {
    id: "gemini-3.6-flash",
    name: "Gemini 3.6 Flash (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["low", "medium", "high"],
    supportsVision: true,
    contextLength: 1065536,
    maxOutputTokens: 65536,
    targetFormat: "gemini",
  },
  {
    id: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high"],
    supportsVision: true,
    contextLength: 1065536,
    maxOutputTokens: 65536,
    targetFormat: "gemini",
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high"],
    supportsVision: true,
    contextLength: 1065536,
    maxOutputTokens: 65536,
    targetFormat: "gemini",
  },
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["low", "medium", "high"],
    supportsVision: true,
    contextLength: 1065536,
    maxOutputTokens: 65536,
    targetFormat: "gemini",
  },
  {
    id: "gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["low", "medium", "high"],
    supportsVision: true,
    contextLength: 1065536,
    maxOutputTokens: 65536,
    targetFormat: "gemini",
  },
  {
    id: "garnet-07-15",
    name: "Garnet 07/15 Preview (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["low", "medium", "high"],
    supportsVision: true,
    contextLength: 1065536,
    maxOutputTokens: 65536,
    targetFormat: "gemini",
  },
];
