import type { RegistryModel } from "../providers/shared.ts";

export const FACTORY_RESPONSES_MODELS: RegistryModel[] = [
  {
    id: "gpt-6-astra",
    name: "GPT-6 Astra (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-6-sol",
    name: "GPT-6 Sol (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-6.1-sol",
    name: "GPT-6.1 Sol (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-6-luna",
    name: "GPT-6 Luna (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.6-sol",
    name: "GPT-5.6 Sol (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.6-sol-fast",
    name: "GPT-5.6 Sol Fast (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.6-terra",
    name: "GPT-5.6 Terra (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.6-luna",
    name: "GPT-5.6 Luna (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5 (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.5-fast",
    name: "GPT-5.5 Fast (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.5-pro",
    name: "GPT-5.5 Pro (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.4",
    name: "GPT-5.4 (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.4-fast",
    name: "GPT-5.4 Fast (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 1050000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 Mini (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 400000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.4-mini-fast",
    name: "GPT-5.4 Mini Fast (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 400000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.3-codex",
    name: "GPT-5.3 Codex (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 400000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.3-codex-fast",
    name: "GPT-5.3 Codex Fast (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    contextLength: 400000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.2",
    name: "GPT-5.2 (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 400000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.2-codex",
    name: "GPT-5.2 Codex [Deprecated] (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 400000,
    maxOutputTokens: 128000,
    targetFormat: "openai-responses",
  },
  {
    id: "gpt-5.1-codex-max",
    name: "GPT-5.1 Codex Max [Deprecated] (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 400000,
    maxOutputTokens: 32768,
    targetFormat: "openai-responses",
  },
  {
    id: "grok-4.7",
    name: "Grok 4.7 (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 500000,
    maxOutputTokens: 63356,
    targetFormat: "openai-responses",
  },
  {
    id: "grok-4.6",
    name: "Grok 4.6 (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 263356,
    maxOutputTokens: 63356,
    targetFormat: "openai-responses",
  },
  {
    id: "grok-4.5",
    name: "Grok 4.5 (Factory)",
    toolCalling: true,
    supportsReasoning: true,
    supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    supportsVision: true,
    contextLength: 263356,
    maxOutputTokens: 63356,
    targetFormat: "openai-responses",
  },
];
