import type { RegistryEntry } from "../../../shared.ts";

export const agnes_cnProvider: RegistryEntry = {
  id: "agnes-cn",
  alias: "agnescn",
  format: "openai",
  executor: "default",
  baseUrl: "https://api.agnes-ai.cn/v1/chat/completions",
  modelsUrl: "https://api.agnes-ai.cn/v1/models",
  authType: "apikey",
  authHeader: "bearer",
  passthroughModels: true,
  liveCatalogAuthoritative: true,
  models: [
    {
      id: "agnes-2.0-flash",
      name: "Agnes 2.0 Flash",
      contextLength: 262144,
      maxOutputTokens: 65536,
      supportsReasoning: true,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "agnes-2.5-flash",
      name: "Agnes 2.5 Flash",
      contextLength: 524288,
      maxOutputTokens: 65536,
      supportsReasoning: true,
      supportsVision: true,
      toolCalling: true,
      interleavedField: "reasoning_content",
    },
    {
      id: "agnes-3.0-flash",
      name: "Agnes 3.0 Flash",
      contextLength: 524288,
      maxOutputTokens: 65536,
      supportsReasoning: true,
      supportsVision: true,
      toolCalling: true,
      interleavedField: "reasoning_content",
    },
  ],
};
