import { describe, test } from "node:test";
import assert from "node:assert/strict";

const { translateStatement, SqliteEmulationError } =
  await import("../../../src/lib/db/adapters/postgres/sqlTranslator.ts");
const { splitStatements, tokenize, render } =
  await import("../../../src/lib/db/adapters/postgres/sqlTokenizer.ts");

type Schema = {
  columns: string[];
  columnTypes: Record<string, string>;
  primaryKey: string[];
  uniqueIndexes: string[][];
  identityColumn: string | null;
};

function contextWith(tables: Record<string, Schema>) {
  return { lookupTable: (name: string) => tables[name.toLowerCase()] ?? null };
}

const emptyContext = contextWith({});

function sql(statement: string, ctx = emptyContext): string {
  const translated = translateStatement(statement, ctx);
  return translated.statements.join(";\n");
}

function normalize(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

describe("sqlite to postgres translator", () => {
  test("Placeholders_PositionalAndNamed_BecomeDollarParameters", () => {
    const positional = translateStatement("SELECT * FROM t WHERE a = ? AND b = ?", emptyContext);
    assert.equal(normalize(positional.statements[0]), "SELECT * FROM t WHERE a = $1 AND b = $2");
    assert.equal(positional.paramCount, 2);
    assert.equal(positional.paramNames, null);

    const named = translateStatement("INSERT INTO t (a, b) VALUES (@a, :b)", emptyContext);
    assert.equal(normalize(named.statements[0]), 'INSERT INTO "t" ("a", "b") VALUES ($1, $2)');
    assert.deepEqual(named.paramNames, ["a", "b"]);
  });

  test("Placeholder_FollowedByIs_GetsTextCast", () => {
    assert.equal(
      normalize(sql("SELECT 1 FROM t WHERE (? IS NULL OR name = ?)")),
      "SELECT 1 FROM t WHERE ($1::text IS NULL OR name = $2)"
    );
  });

  test("CreateTable_SqliteTypes_MapToPostgresTypes", () => {
    const out = normalize(
      sql(`CREATE TABLE IF NOT EXISTS items (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL COLLATE NOCASE,
        enabled BOOLEAN DEFAULT 1,
        score REAL,
        blob BLOB,
        parent_id INTEGER REFERENCES items(id) ON DELETE CASCADE,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        FOREIGN KEY (parent_id) REFERENCES items(id)
      )`)
    );
    assert.equal(
      out,
      'CREATE TABLE IF NOT EXISTS "items" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" TEXT NOT NULL, "enabled" BIGINT DEFAULT 1, "score" DOUBLE PRECISION, "blob" BYTEA, "parent_id" BIGINT REFERENCES "items"("id") ON DELETE CASCADE, "created_at" TEXT DEFAULT (omniroute_datetime(\'now\')), "updated_at" TEXT NOT NULL DEFAULT (omniroute_datetime(\'now\')), FOREIGN KEY ("parent_id") REFERENCES "items"("id"))'
    );
  });

  test("CreateTable_RowidTable_GetsHiddenIdentityColumn", () => {
    const out = normalize(
      sql("CREATE TABLE call_logs (id TEXT PRIMARY KEY, timestamp TEXT NOT NULL) WITHOUT ROWID")
    );
    assert.ok(out.endsWith('"rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY)'), out);
  });

  test("CreateTable_DoubleQuotedDefault_BecomesStringLiteral", () => {
    const out = normalize(sql('CREATE TABLE t (cache_source TEXT DEFAULT "upstream")'));
    assert.equal(out, `CREATE TABLE "t" ("cache_source" TEXT DEFAULT 'upstream')`);
  });

  test("InsertOrReplace_KnownTable_BecomesOnConflictUpsert", () => {
    const ctx = contextWith({
      key_value: {
        columns: ["namespace", "key", "value", "updated_at"],
        columnTypes: {},
        primaryKey: ["namespace", "key"],
        uniqueIndexes: [],
        identityColumn: null,
      },
    });
    const out = normalize(
      sql("INSERT OR REPLACE INTO key_value (namespace, key, value) VALUES (?, ?, ?)", ctx)
    );
    assert.equal(
      out,
      'INSERT INTO "key_value" ("namespace", "key", "value") VALUES ($1, $2, $3) ON CONFLICT ("namespace", "key") DO UPDATE SET "value" = EXCLUDED."value", "updated_at" = DEFAULT'
    );
  });

  test("InsertOrReplace_UnknownTable_Throws", () => {
    assert.throws(() => sql("INSERT OR REPLACE INTO nope (a) VALUES (1)"), SqliteEmulationError);
  });

  test("InsertOrIgnore_BecomesOnConflictDoNothing", () => {
    const out = normalize(sql("INSERT OR IGNORE INTO t (a) VALUES (1) RETURNING id"));
    assert.equal(out, 'INSERT INTO "t" ("a") VALUES (1) ON CONFLICT DO NOTHING RETURNING id');
  });

  test("Insert_IdentityTable_AppendsReturningForLastInsertRowid", () => {
    const ctx = contextWith({
      items: {
        columns: ["id", "name"],
        columnTypes: { id: "BIGINT", name: "TEXT" },
        primaryKey: ["id"],
        uniqueIndexes: [],
        identityColumn: "id",
      },
    });
    const translated = translateStatement("INSERT INTO items (name) VALUES (?)", ctx);
    assert.equal(
      normalize(translated.statements[0]),
      'INSERT INTO "items" ("name") VALUES ($1) RETURNING "id" AS "__omniroute_rowid"'
    );
    assert.equal(translated.returningColumn, "__omniroute_rowid");
  });

  test("Functions_DateTimeAndJson_UseHelpers", () => {
    const out = normalize(
      sql(
        "SELECT datetime('now'), datetime('now', '-1 hour'), strftime('%Y-%m-%d', created_at), unixepoch('now'), json_extract(data, '$.a'), json_valid(data), json_type(data, '$.b'), typeof(x), IFNULL(a, b), MAX(1, 2), MIN(a) FROM t"
      )
    );
    assert.equal(
      out,
      "SELECT omniroute_datetime('now'), omniroute_datetime('now', '-1 hour'), omniroute_strftime('%Y-%m-%d', created_at), omniroute_unixepoch('now'), omniroute_json_extract(data, '$.a'), omniroute_json_valid(data), omniroute_json_type(data, '$.b'), omniroute_typeof(x), COALESCE(a, b), GREATEST(1, 2), MIN(a) FROM t"
    );
  });

  test("Cast_ToIntegerAndReal_UseLenientHelpers", () => {
    assert.equal(
      normalize(sql("SELECT CAST(x AS INTEGER), CAST(y AS REAL), CAST(z AS TEXT) FROM t")),
      "SELECT omniroute_to_integer(x), omniroute_to_real(y), (z)::text FROM t"
    );
  });

  test("JsonExtract_ComparedToNumber_IsCastToReal", () => {
    assert.equal(
      normalize(sql("SELECT 1 FROM t WHERE json_extract(data, '$.n') = 1")),
      "SELECT 1 FROM t WHERE omniroute_to_real(omniroute_json_extract(data, '$.n')) = 1"
    );
  });

  test("JsonValid_ComparedToLiteral_BecomesBoolean", () => {
    assert.equal(
      normalize(sql("SELECT 1 FROM t WHERE json_valid(a) = 1 AND json_valid(b) = 0")),
      "SELECT 1 FROM t WHERE omniroute_json_valid(a) AND NOT omniroute_json_valid(b)"
    );
  });

  test("Operators_LikeIsGlobAndDoubleEquals_AreRewritten", () => {
    assert.equal(
      normalize(
        sql(
          "SELECT 1 FROM t WHERE a LIKE 'x%' AND b == 2 AND c IS NOT 0 AND d IS 'z' AND e NOT GLOB '*[^0-9]*'"
        )
      ),
      "SELECT 1 FROM t WHERE a ILIKE 'x%' AND b = 2 AND c IS DISTINCT FROM 0 AND d IS NOT DISTINCT FROM 'z' AND e !~ '^.*[^0-9].*$'"
    );
  });

  test("CollateNocase_InOrderByAndEquality_UsesLower", () => {
    assert.equal(
      normalize(
        sql("SELECT * FROM t WHERE name = ? COLLATE NOCASE ORDER BY name COLLATE NOCASE ASC")
      ),
      "SELECT * FROM t WHERE lower(name) = lower($1) ORDER BY lower(name) ASC"
    );
  });

  test("BareColumn_InBooleanContext_ComparesAgainstZero", () => {
    assert.equal(
      normalize(sql("SELECT id FROM t WHERE enabled AND NOT deleted OR t.flag")),
      "SELECT id FROM t WHERE (enabled <> 0) AND NOT (deleted <> 0) OR (t.flag <> 0)"
    );
  });

  test("Case_MixedBooleanAndIntegerBranches_BecomesBoolean", () => {
    assert.equal(
      normalize(sql("SELECT 1 FROM t WHERE CASE WHEN a THEN b != 'x' ELSE 0 END")),
      "SELECT 1 FROM t WHERE CASE WHEN (a <> 0) THEN b != 'x' ELSE FALSE END"
    );
  });

  test("MixedCaseAlias_IsQuoted", () => {
    assert.equal(
      normalize(sql("SELECT COUNT(*) AS activeCount FROM t ORDER BY activeCount")),
      'SELECT COUNT(*) AS "activeCount" FROM t ORDER BY "activeCount"'
    );
  });

  test("JsonEach_InJoin_BecomesLateralHelper", () => {
    assert.equal(
      normalize(
        sql("SELECT m.value FROM key_value kv JOIN json_each(kv.value) m WHERE kv.key = 'x'")
      ),
      `SELECT m.value FROM key_value kv CROSS JOIN LATERAL omniroute_json_each(kv.value) AS "m" WHERE kv.key = 'x'`
    );
  });

  test("Rowid_AsAlias_IsLeftAlone", () => {
    const ctx = contextWith({
      items: {
        columns: ["id", "name"],
        columnTypes: { id: "BIGINT", name: "TEXT" },
        primaryKey: ["id"],
        uniqueIndexes: [],
        identityColumn: "id",
      },
    });
    assert.equal(
      normalize(sql("SELECT id AS rowId, name FROM items WHERE rowid > ?", ctx)),
      'SELECT id AS "rowId", name FROM items WHERE id > $1'
    );
  });

  test("Rowid_OnIdentityTable_BecomesPrimaryKey", () => {
    const ctx = contextWith({
      items: {
        columns: ["id", "name"],
        columnTypes: { id: "BIGINT", name: "TEXT" },
        primaryKey: ["id"],
        uniqueIndexes: [],
        identityColumn: "id",
      },
    });
    assert.equal(
      normalize(sql("SELECT rowid AS seq FROM items WHERE rowid > ? ORDER BY rowid", ctx)),
      "SELECT id AS seq FROM items WHERE id > $1 ORDER BY id"
    );
  });

  test("AlterTable_AddColumn_IsIdempotent", () => {
    assert.equal(
      normalize(sql("ALTER TABLE t ADD COLUMN extra INTEGER NOT NULL DEFAULT 0 REFERENCES x(id)")),
      'ALTER TABLE "t" ADD COLUMN IF NOT EXISTS "extra" BIGINT NOT NULL DEFAULT 0'
    );
    const ctx = contextWith({
      x: {
        columns: ["id"],
        columnTypes: { id: "BIGINT" },
        primaryKey: ["id"],
        uniqueIndexes: [],
        identityColumn: "id",
      },
    });
    assert.equal(
      normalize(
        sql("ALTER TABLE t ADD COLUMN owner INTEGER REFERENCES x(id) ON DELETE SET NULL", ctx)
      ),
      'ALTER TABLE "t" ADD COLUMN IF NOT EXISTS "owner" BIGINT REFERENCES "x"("id") ON DELETE SET NULL'
    );
    assert.equal(
      normalize(sql("ALTER TABLE t DROP COLUMN extra")),
      'ALTER TABLE "t" DROP COLUMN IF EXISTS "extra"'
    );
    assert.equal(normalize(sql("ALTER TABLE t RENAME TO u")), 'ALTER TABLE "t" RENAME TO "u"');
  });

  test("DropStatements_TranslateWithCascade", () => {
    assert.equal(sql("DROP TABLE IF EXISTS t"), 'DROP TABLE IF EXISTS "t" CASCADE');
    assert.equal(
      sql("DROP TRIGGER IF EXISTS trg_x"),
      'DROP FUNCTION IF EXISTS "omniroute_trg_trg_x"() CASCADE'
    );
    assert.equal(sql("DROP INDEX IF EXISTS idx_x"), 'DROP INDEX IF EXISTS "idx_x"');
  });

  test("CreateVirtualTable_ThrowsNoSuchModule", () => {
    assert.throws(
      () => sql("CREATE VIRTUAL TABLE memory_fts USING fts5(content)"),
      /no such module: fts5/
    );
  });

  test("Pragma_IsReportedNotTranslated", () => {
    const translated = translateStatement("PRAGMA table_info(items)", emptyContext);
    assert.equal(translated.kind, "pragma");
    assert.equal(translated.pragma, "table_info(items)");
  });

  test("VacuumAndReindex_AreNoops", () => {
    assert.equal(translateStatement("VACUUM", emptyContext).kind, "noop");
    assert.equal(translateStatement("REINDEX", emptyContext).kind, "noop");
  });

  test("Transactions_NormalizeSqliteForms", () => {
    assert.deepEqual(translateStatement("BEGIN IMMEDIATE TRANSACTION", emptyContext).statements, [
      "BEGIN",
    ]);
    assert.deepEqual(translateStatement("END TRANSACTION", emptyContext).statements, ["COMMIT"]);
    assert.deepEqual(translateStatement("ROLLBACK TO SAVEPOINT sp1", emptyContext).statements, [
      'ROLLBACK TO SAVEPOINT "sp1"',
    ]);
  });

  test("Trigger_WithWhenAndBody_BecomesPlpgsqlFunction", () => {
    const translated = translateStatement(
      `CREATE TRIGGER IF NOT EXISTS trg_retire AFTER INSERT ON provider_connections
       WHEN lower(trim(NEW.provider, ' ' || char(9))) IN ('gone')
       BEGIN
         UPDATE provider_connections SET is_active = 0, updated_at = datetime('now') WHERE id = NEW.id;
         SELECT RAISE(ABORT, 'nope') WHERE NEW.provider = 'boom';
       END`,
      emptyContext
    );
    assert.equal(translated.statements.length, 3);
    const [fn, drop, create] = translated.statements;
    assert.match(
      fn,
      /CREATE OR REPLACE FUNCTION "omniroute_trg_trg_retire"\(\) RETURNS trigger LANGUAGE plpgsql/
    );
    assert.match(
      fn,
      /IF NOT \(lower\(btrim\(NEW\.provider, ' ' \|\| \(chr\(\(9\)::int\)\)\)\) IN \('gone'\)\) THEN RETURN NULL; END IF;/
    );
    assert.match(
      fn,
      /UPDATE "provider_connections" SET is_active = 0, updated_at = omniroute_datetime\('now'\) WHERE id = NEW\.id;/
    );
    assert.match(fn, /IF NEW\.provider = 'boom' THEN RAISE EXCEPTION 'nope'; END IF;/);
    assert.equal(drop, 'DROP TRIGGER IF EXISTS "trg_retire" ON "provider_connections"');
    assert.equal(
      create,
      'CREATE TRIGGER "trg_retire" AFTER INSERT ON "provider_connections" FOR EACH ROW EXECUTE FUNCTION "omniroute_trg_trg_retire"()'
    );
  });

  test("Trigger_UpdateOfColumns_KeepsColumnList", () => {
    const translated = translateStatement(
      "CREATE TRIGGER t_upd AFTER UPDATE OF provider, is_active ON provider_connections BEGIN DELETE FROM x WHERE id = OLD.id; END",
      emptyContext
    );
    assert.match(
      translated.statements[2],
      /AFTER UPDATE OF "provider", "is_active" ON "provider_connections"/
    );
  });

  test("SplitStatements_KeepsTriggerBodiesTogether", () => {
    const parts = splitStatements(`
      CREATE TABLE a (id INTEGER);
      -- a comment; with a semicolon
      CREATE TRIGGER t AFTER INSERT ON a BEGIN DELETE FROM a WHERE id = 1; UPDATE a SET id = 2; END;
      INSERT INTO a VALUES (1);
    `);
    assert.equal(parts.length, 3);
    assert.match(parts[1], /^CREATE TRIGGER/);
    assert.match(parts[1], /END$/);
  });

  test("Tokenizer_RoundTripsStringsAndQuotedIdentifiers", () => {
    const text = `SELECT "group", 'it''s', x'ff', 1.5e3 FROM t`;
    assert.equal(render(tokenize(text)), `SELECT "group", 'it''s', '\\xff'::bytea, 1.5e3 FROM t`);
  });

  test("CharTrimAndRound_UsePostgresEquivalents", () => {
    assert.equal(
      normalize(
        sql("SELECT trim(a, ' '), char(9, 10), round(x, 2), instr(a, 'b'), hex(a), random() FROM t")
      ),
      "SELECT btrim(a, ' '), (chr((9)::int) || chr((10)::int)), round((x)::numeric, 2), strpos(a, 'b'), omniroute_hex(a), omniroute_random() FROM t"
    );
  });

  test("GroupConcatAndTotal_UseAggregates", () => {
    assert.equal(
      normalize(
        sql("SELECT GROUP_CONCAT(DISTINCT kind), GROUP_CONCAT(name, ';'), total(cost) FROM t")
      ),
      "SELECT string_agg(DISTINCT (kind)::text, ','), string_agg((name)::text, ';'), (COALESCE(SUM(cost), 0))::double precision FROM t"
    );
  });
});
