// GENERATED by scripts/i18n/generate-route-namespaces.mjs — do not edit by hand.
import { SectionI18nProvider } from "@/i18n/SectionI18nProvider";
import routeNamespaces from "@/i18n/routeNamespaces.generated.json";

/**
 * Home route (/home) i18n provider — serves the namespaces used by the client
 * components under `src/app/(dashboard)/home/` and the `dashboard/`
 * companions its page imports (see scripts/i18n/generate-route-namespaces.mjs).
 */
export default function HomeSectionLayout({ children }: { children: React.ReactNode }) {
  return <SectionI18nProvider namespaces={routeNamespaces.home}>{children}</SectionI18nProvider>;
}
