name: Cargo Audit

on:
  push:
    paths:
      - ".github/workflows/cargo-audit.yml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Audit
        uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
